package live.vayusat.alerts.data.remote

import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import live.vayusat.alerts.data.model.RemoteConfig
import live.vayusat.alerts.data.model.RemoteUiBlock

/**
 * Service managing Server-Driven UI (SDUI) configurations and remote feature toggles.
 * Provides safe, schema-validated content blocks without dynamic code execution.
 */
class RemoteConfigService {

    private val _config = MutableStateFlow(createDefaultConfig())
    val config: StateFlow<RemoteConfig> = _config.asStateFlow()

    fun updateConfig(newConfig: RemoteConfig) {
        _config.value = newConfig
    }

    companion object {
        fun createDefaultConfig(): RemoteConfig {
            return RemoteConfig(
                version = "10.0.0",
                minSupportedAppVersion = "1.0.0",
                features = mapOf(
                    "enable_radar_overlay" to true,
                    "enable_satellite_stream" to true,
                    "enable_community_reports" to false,
                    "enable_ai_advisory_explainer" to true
                ),
                uiBlocks = listOf(
                    RemoteUiBlock(
                        id = "block_statutory_notice",
                        type = "INFO_BANNER",
                        title = "VAYU Meteorological Research Advisory",
                        body = "All track projections and severity ratings are generated by VAYU deep learning models. For evacuation orders and statutory directives, please follow your local State Disaster Management Authority (SDMA) & IMD.",
                        priority = 100,
                        actionLabel = "Review Guidelines",
                        actionUrl = "vayu://guidelines"
                    ),
                    RemoteUiBlock(
                        id = "block_emergency_helpline",
                        type = "HELPLINE_CARD",
                        title = "Emergency Contact Directory",
                        body = "National Disaster Helpline: 1078 | Coastal Guard Search & Rescue: 1554",
                        priority = 50,
                        actionLabel = "Call 1078",
                        actionUrl = "tel:1078"
                    )
                )
            )
        }
    }
}
