import React from 'react';
import { Sparkles, Radio, History, TestTube, AlertTriangle } from 'lucide-react';

/**
 * DataTypeBadge
 * Visually distinguishes data credibility for users and SIH judges:
 * - "Live Data" (genuine real-time sensors, buoy, or connected satellite)
 * - "AI Prediction" (neural network forecast, GRU Seq2Seq, ResNet18 classification)
 * - "Historical Data" (archived recorded cyclone best-track)
 * - "Demo/Sample Data" (calibrated benchmark scenario or when live API is unavailable)
 * - "Data Unavailable" (when sensor is offline or feed is unmonitored)
 */
export default function DataTypeBadge({
  type = 'demo',
  isLiveAvailable = null,
  label = null,
  size = 'sm',
  className = '',
  isHindi = false
}) {
  // If requested type is 'live' but backend/feed is not live, downgrade to 'unavailable' or 'demo'
  let resolvedType = type;
  if (type === 'live' && isLiveAvailable === false) {
    resolvedType = 'demo';
  }

  const CONFIGS = {
    live: {
      defaultLabel: isHindi ? 'लाइव डेटा' : 'Live Data',
      dotClass: 'bg-emerald-500 animate-pulse',
      badgeClass: 'bg-emerald-50 dark:bg-emerald-950/60 text-emerald-700 dark:text-emerald-300 border-emerald-200 dark:border-emerald-800/60',
      icon: Radio,
      tooltip: isHindi ? 'वास्तविक समय में प्राप्त अवलोकन डेटा' : 'Genuine real-time sensor observation'
    },
    ai: {
      defaultLabel: isHindi ? 'एआई पूर्वानुमान' : 'AI Prediction',
      dotClass: 'bg-sky-500',
      badgeClass: 'bg-sky-50 dark:bg-sky-950/60 text-sky-700 dark:text-sky-300 border-sky-200 dark:border-sky-800/60',
      icon: Sparkles,
      tooltip: isHindi ? 'डीप लर्निंग न्यूरल नेटवर्क द्वारा जनित प्रक्षेपवक्र व तीव्रता' : 'Generated by GRU Seq2Seq / ResNet18 deep neural models'
    },
    historical: {
      defaultLabel: isHindi ? 'ऐतिहासिक डेटा' : 'Historical Data',
      dotClass: 'bg-amber-500',
      badgeClass: 'bg-amber-50 dark:bg-amber-950/60 text-amber-800 dark:text-amber-300 border-amber-200 dark:border-amber-800/60',
      icon: History,
      tooltip: isHindi ? 'आईएमडी के आधिकारिक ऐतिहासिक अभिलेख से सत्यापित ट्रैक' : 'Recorded IMD official best-track benchmark archive'
    },
    demo: {
      defaultLabel: isHindi ? 'डेमो / नमूना डेटा' : 'Demo / Sample Data',
      dotClass: 'bg-purple-500',
      badgeClass: 'bg-purple-50 dark:bg-purple-950/60 text-purple-700 dark:text-purple-300 border-purple-200 dark:border-purple-800/60',
      icon: TestTube,
      tooltip: isHindi ? 'लाइव एपीआई अनुपलब्ध; कैलिब्रेटेड सिमुलेशन डेटा प्रदर्शित है' : 'Live feed offline; displaying calibrated benchmark scenario'
    },
    unavailable: {
      defaultLabel: isHindi ? 'डेटा वर्तमान में अनुपलब्ध' : 'Data Currently Unavailable',
      dotClass: 'bg-slate-400',
      badgeClass: 'bg-slate-100 dark:bg-slate-800 text-slate-600 dark:text-slate-300 border-slate-300 dark:border-slate-700',
      icon: AlertTriangle,
      tooltip: isHindi ? 'सेंसर फीड वर्तमान में सक्रिय नहीं है' : 'Sensor stream offline / awaiting satellite pass'
    }
  };

  const currentConfig = CONFIGS[resolvedType] || CONFIGS.demo;
  const IconComponent = currentConfig.icon;
  const displayLabel = label || currentConfig.defaultLabel;

  const sizeClasses = size === 'xs'
    ? 'px-1.5 py-0.5 text-[9px] gap-1'
    : size === 'md'
    ? 'px-2.5 py-1 text-xs gap-1.5'
    : 'px-2 py-0.5 text-[10px] gap-1';

  return (
    <span
      title={currentConfig.tooltip}
      className={`inline-flex items-center font-mono font-bold uppercase tracking-wider rounded-full border shadow-2xs backdrop-blur-md transition-all ${currentConfig.badgeClass} ${sizeClasses} ${className}`}
    >
      <span className={`w-1.5 h-1.5 rounded-full ${currentConfig.dotClass}`} />
      <IconComponent className="w-2.5 h-2.5 opacity-80" />
      <span>{displayLabel}</span>
    </span>
  );
}
