import React, { useState, useEffect, useRef, useMemo } from 'react';
import { 
  Sparkles, Bot, X, Send, RefreshCw, AlertTriangle, 
  Wind, Gauge, Activity, ShieldAlert, Clock, ArrowRight,
  Compass, Eye, CheckCircle2, ChevronDown, RotateCcw
} from 'lucide-react';
import { useAnalysisSession } from '../context/AnalysisSessionContext';
import { buildCyclonePromptContext } from '../services/cycloneContextSerializer';
import { explainCyclone, askAnalyst } from '../services/puterAiService';

/**
 * Quick Action Prompts Configuration
 */
const QUICK_ACTIONS = [
  {
    id: 'summarize',
    label: 'Summarize Current Storm',
    icon: Sparkles,
    type: 'explain'
  },
  {
    id: 'dvorak',
    label: 'Explain Dvorak Analysis',
    icon: Eye,
    type: 'ask',
    prompt: 'Explain the Dvorak morphology analysis, convective pattern organization, and T-number intensity classification for this storm.'
  },
  {
    id: 'trajectory',
    label: 'Analyze Trajectory',
    icon: Compass,
    type: 'ask',
    prompt: 'Analyze the predicted 72-hour trajectory, recurvature tendency, and movement milestones generated by the VAYU GRU model.'
  },
  {
    id: 'landfall',
    label: 'Assess Landfall Risk',
    icon: ShieldAlert,
    type: 'ask',
    prompt: 'Assess the projected landfall risk, timing window, target coastal districts, and expected peak wind / surge hazards.'
  },
  {
    id: 'confidence',
    label: 'Explain Model Confidence',
    icon: Activity,
    type: 'ask',
    prompt: 'Explain the confidence levels and potential uncertainties of the MobileNetV3 center fix and ResNet18 Dvorak classification outputs.'
  }
];

/**
 * Safe operational message text formatter.
 * Renders paragraphs, bullet points, and section headers cleanly without dangerouslySetInnerHTML.
 */
function FormattedMessageText({ text }) {
  if (!text) return null;

  const lines = text.split('\n');

  return (
    <div className="space-y-2 text-xs sm:text-[13px] leading-relaxed select-text">
      {lines.map((line, idx) => {
        const trimmed = line.trim();
        if (!trimmed) {
          return <div key={idx} className="h-1.5" />;
        }

        // Section Headings (e.g., ### Heading or 1. HEADING:)
        if (trimmed.startsWith('###') || trimmed.startsWith('##') || /^[1-4]\.\s+[A-Z\s&]+:/.test(trimmed)) {
          const cleanHeading = trimmed.replace(/^#{1,4}\s*/, '');
          return (
            <div key={idx} className="pt-2 font-bold text-slate-900 dark:text-white flex items-center gap-1.5 border-b border-slate-100 dark:border-slate-800 pb-1">
              <span className="w-1.5 h-1.5 rounded-full bg-sky-500" />
              <span>{cleanHeading}</span>
            </div>
          );
        }

        // Bullet point item
        if (trimmed.startsWith('•') || trimmed.startsWith('-') || trimmed.startsWith('*')) {
          const bulletContent = trimmed.replace(/^[•\-\*]\s*/, '');
          return (
            <div key={idx} className="flex items-start gap-2 pl-2">
              <span className="text-sky-500 font-bold shrink-0 mt-0.5">•</span>
              <span className="text-slate-700 dark:text-slate-200">{renderInlineFormatting(bulletContent)}</span>
            </div>
          );
        }

        // Standard Paragraph
        return (
          <p key={idx} className="text-slate-700 dark:text-slate-200">
            {renderInlineFormatting(trimmed)}
          </p>
        );
      })}
    </div>
  );
}

/**
 * Helper to render bold keywords (e.g., **text**)
 */
function renderInlineFormatting(str) {
  const parts = str.split(/(\*\*[^*]+\*\*)/g);
  return parts.map((part, i) => {
    if (part.startsWith('**') && part.endsWith('**')) {
      return (
        <strong key={i} className="font-semibold text-slate-900 dark:text-white">
          {part.slice(2, -2)}
        </strong>
      );
    }
    return part;
  });
}

/**
 * VAYU AI Analyst Drawer Component
 * ----------------------------------------------------
 * High-performance, context-grounded AI copilot for operational forecasting officers.
 */
export default function VayuAiAnalystDrawer({ isOpen, onClose }) {
  const session = useAnalysisSession();
  const { currentInput, detectionResult, classificationResult } = session;

  const [messages, setMessages] = useState([]);
  const [inputText, setInputText] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const [activeSessionId, setActiveSessionId] = useState(currentInput?.sessionId);
  const [lastError, setLastError] = useState(null);

  const messagesEndRef = useRef(null);
  const inputRef = useRef(null);

  // Derive standardized serialized prompt context from current active session
  const promptContext = useMemo(() => {
    return buildCyclonePromptContext(session);
  }, [session]);

  const activeStormName = promptContext.storm_identification?.name || currentInput?.name;
  const hasActiveSession = Boolean(
    activeStormName &&
    (detectionResult?.cyclone_detected || classificationResult || currentInput?.sourceType === 'benchmark')
  );

  // Extract human-readable summary badges
  const summaryCenter = promptContext.current_observation?.estimated_center?.formatted;
  const summaryWind = promptContext.current_observation?.current_wind_speed_kmh;
  const summaryPressure = promptContext.current_observation?.current_central_pressure_hpa;
  const summaryPattern = promptContext.classification?.primary_pattern;
  const summaryTNum = promptContext.classification?.dvorak_t_number;
  const summaryLandfall = promptContext.trajectory?.landfall_projection;

  // Clear conversation if session changes to prevent cross-storm context leakage
  useEffect(() => {
    if (currentInput?.sessionId && currentInput.sessionId !== activeSessionId) {
      setActiveSessionId(currentInput.sessionId);
      setMessages([]);
      setLastError(null);
    }
  }, [currentInput?.sessionId, activeSessionId]);

  // Auto-scroll to bottom of conversation
  useEffect(() => {
    if (isOpen) {
      messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
    }
  }, [messages, isLoading, isOpen]);

  // Focus input when opened
  useEffect(() => {
    if (isOpen && hasActiveSession) {
      setTimeout(() => inputRef.current?.focus(), 150);
    }
  }, [isOpen, hasActiveSession]);

  /**
   * Dispatches an AI request via puterAiService and updates the message log.
   */
  const executeAiRequest = async ({ actionType, userPrompt, actionLabel }) => {
    if (!hasActiveSession) return;
    if (isLoading) return;

    setIsLoading(true);
    setLastError(null);

    // Append user message if custom question or quick action
    const userMessageId = `msg_user_${Date.now()}`;
    setMessages(prev => [
      ...prev,
      {
        id: userMessageId,
        role: 'user',
        text: actionLabel || userPrompt,
        timestamp: new Date().toLocaleTimeString('en-IN', { hour: '2-digit', minute: '2-digit', hour12: true })
      }
    ]);

    try {
      let response;
      if (actionType === 'explain') {
        response = await explainCyclone(promptContext);
      } else {
        response = await askAnalyst(userPrompt, promptContext);
      }

      if (response && response.success && response.text) {
        setMessages(prev => [
          ...prev,
          {
            id: `msg_ai_${Date.now()}`,
            role: 'assistant',
            text: response.text,
            timestamp: new Date().toLocaleTimeString('en-IN', { hour: '2-digit', minute: '2-digit', hour12: true })
          }
        ]);
      } else {
        const errorMsg = response?.error || 'VAYU AI Analyst is temporarily unavailable. Your underlying VAYU model results are still available.';
        setLastError(errorMsg);
        setMessages(prev => [
          ...prev,
          {
            id: `msg_err_${Date.now()}`,
            role: 'error',
            text: errorMsg,
            retryAction: { actionType, userPrompt, actionLabel }
          }
        ]);
      }
    } catch (err) {
      const errorMsg = err?.message || 'VAYU AI Analyst is temporarily unavailable. Your underlying VAYU model results are still available.';
      setLastError(errorMsg);
      setMessages(prev => [
        ...prev,
        {
          id: `msg_err_${Date.now()}`,
          role: 'error',
          text: errorMsg,
          retryAction: { actionType, userPrompt, actionLabel }
        }
      ]);
    } finally {
      setIsLoading(false);
    }
  };

  const handleCustomSubmit = (e) => {
    e?.preventDefault();
    if (!inputText.trim() || isLoading) return;
    const query = inputText.trim();
    setInputText('');
    executeAiRequest({ actionType: 'ask', userPrompt: query });
  };

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-50 flex justify-end">
      {/* Backdrop */}
      <div 
        className="fixed inset-0 bg-black/40 backdrop-blur-xs transition-opacity animate-in fade-in duration-200"
        onClick={onClose}
      />

      {/* Drawer Container */}
      <aside 
        className="relative z-10 w-full sm:w-[480px] lg:w-[520px] h-full bg-white dark:bg-slate-900 border-l border-slate-200 dark:border-slate-800 shadow-2xl flex flex-col overflow-hidden animate-in slide-in-from-right duration-300"
        onClick={e => e.stopPropagation()}
      >
        {/* Top Header */}
        <div className="px-4 sm:px-5 py-3.5 border-b border-slate-100 dark:border-slate-800 flex items-center justify-between bg-slate-50/80 dark:bg-slate-900/80 backdrop-blur-md shrink-0">
          <div className="flex items-center gap-2.5">
            <div className="w-8 h-8 rounded-xl bg-gradient-to-tr from-sky-600 to-cyan-500 text-white flex items-center justify-center shadow-sm">
              <Bot className="w-4 h-4" />
            </div>
            <div>
              <div className="flex items-center gap-2">
                <h3 className="font-bold text-sm text-slate-900 dark:text-white tracking-tight">
                  VAYU AI Analyst
                </h3>
                <span className="inline-flex items-center gap-1 text-[10px] font-semibold px-2 py-0.5 rounded-full bg-sky-50 dark:bg-sky-950/60 text-sky-700 dark:text-sky-300 border border-sky-200/50 dark:border-sky-800/50">
                  <span className={`w-1.5 h-1.5 rounded-full ${isLoading ? 'bg-amber-500 animate-ping' : 'bg-emerald-500'}`} />
                  {isLoading ? 'Analyzing...' : 'Puter AI Ready'}
                </span>
              </div>
              <p className="text-[10px] text-slate-500 dark:text-slate-400 font-mono leading-tight mt-0.5">
                Meteorological Synthesis & Guidance Layer
              </p>
            </div>
          </div>

          <div className="flex items-center gap-1">
            {messages.length > 0 && (
              <button
                onClick={() => { setMessages([]); setLastError(null); }}
                className="p-1.5 text-slate-400 hover:text-slate-700 dark:hover:text-slate-200 hover:bg-slate-100 dark:hover:bg-slate-800 rounded-lg transition-colors cursor-pointer"
                title="Clear Conversation"
              >
                <RotateCcw className="w-4 h-4" />
              </button>
            )}
            <button
              onClick={onClose}
              className="p-1.5 text-slate-400 hover:text-slate-700 dark:hover:text-slate-200 hover:bg-slate-100 dark:hover:bg-slate-800 rounded-lg transition-colors cursor-pointer"
              title="Close Drawer"
            >
              <X className="w-4 h-4" />
            </button>
          </div>
        </div>

        {/* Active Session Context Summary Card */}
        <div className="px-4 py-3 bg-slate-100/70 dark:bg-slate-800/40 border-b border-slate-200/60 dark:border-slate-800/60 shrink-0">
          <div className="flex items-center justify-between mb-2">
            <span className="text-[10px] font-bold uppercase tracking-wider text-slate-400 dark:text-slate-500">
              Active Cyclone Session
            </span>
            <span className="text-[10px] font-mono text-sky-600 dark:text-sky-400 font-semibold truncate max-w-[200px]">
              {promptContext.storm_identification?.basin || 'North Indian Ocean'}
            </span>
          </div>

          {hasActiveSession ? (
            <div className="space-y-2">
              <div className="flex items-center justify-between">
                <span className="text-xs font-bold text-slate-900 dark:text-white truncate">
                  {activeStormName}
                </span>
                {summaryCenter && (
                  <span className="text-[11px] font-mono text-slate-600 dark:text-slate-300 font-medium bg-white dark:bg-slate-800 px-2 py-0.5 rounded border border-slate-200/60 dark:border-slate-700">
                    {summaryCenter}
                  </span>
                )}
              </div>

              {/* Metrics Pills */}
              <div className="grid grid-cols-3 gap-1.5 pt-0.5">
                <div className="p-1.5 rounded-lg bg-white dark:bg-slate-800 border border-slate-200/60 dark:border-slate-700 text-center">
                  <span className="text-[9px] text-slate-400 uppercase font-mono block">Wind</span>
                  <span className="text-xs font-bold text-slate-800 dark:text-slate-200 font-mono">
                    {summaryWind !== null ? `${summaryWind} km/h` : 'N/A'}
                  </span>
                </div>
                <div className="p-1.5 rounded-lg bg-white dark:bg-slate-800 border border-slate-200/60 dark:border-slate-700 text-center">
                  <span className="text-[9px] text-slate-400 uppercase font-mono block">Pressure</span>
                  <span className="text-xs font-bold text-slate-800 dark:text-slate-200 font-mono">
                    {summaryPressure !== null ? `${summaryPressure} hPa` : 'N/A'}
                  </span>
                </div>
                <div className="p-1.5 rounded-lg bg-white dark:bg-slate-800 border border-slate-200/60 dark:border-slate-700 text-center">
                  <span className="text-[9px] text-slate-400 uppercase font-mono block">Dvorak</span>
                  <span className="text-xs font-bold text-sky-600 dark:text-sky-400 font-mono">
                    {summaryTNum || (summaryPattern ? summaryPattern.split(' ')[0] : 'T-Fix')}
                  </span>
                </div>
              </div>

              {/* Landfall Alert Chip if active */}
              {summaryLandfall?.is_landfall_projected && (
                <div className="flex items-center gap-1.5 px-2.5 py-1 rounded-lg bg-amber-50 dark:bg-amber-950/40 border border-amber-200 dark:border-amber-800/50 text-[11px] text-amber-800 dark:text-amber-300 font-medium">
                  <ShieldAlert className="w-3.5 h-3.5 text-amber-600 shrink-0" />
                  <span className="truncate">
                    Landfall: {summaryLandfall.target_coast || 'Coastal Sector'} ({summaryLandfall.estimated_time || 'Projected'})
                  </span>
                </div>
              )}
            </div>
          ) : (
            <div className="p-3 rounded-xl bg-amber-50 dark:bg-amber-950/30 border border-amber-200 dark:border-amber-900/40 flex items-start gap-2">
              <AlertTriangle className="w-4 h-4 text-amber-600 shrink-0 mt-0.5" />
              <div className="text-xs text-amber-800 dark:text-amber-200">
                <span className="font-bold block">No Active Cyclone Loaded</span>
                <span className="text-[11px]">
                  Select or load a cyclone frame in Satellite Studio or Trajectory Lab to activate the AI Analyst.
                </span>
              </div>
            </div>
          )}
        </div>

        {/* Quick Action Chips */}
        {hasActiveSession && (
          <div className="px-4 py-2.5 border-b border-slate-100 dark:border-slate-800 bg-white dark:bg-slate-900 overflow-x-auto shrink-0 scrollbar-none">
            <div className="flex items-center gap-1.5 min-w-max">
              {QUICK_ACTIONS.map((action) => {
                const IconComponent = action.icon;
                return (
                  <button
                    key={action.id}
                    disabled={isLoading}
                    onClick={() => {
                      if (action.type === 'explain') {
                        executeAiRequest({ actionType: 'explain', actionLabel: action.label });
                      } else {
                        executeAiRequest({ actionType: 'ask', userPrompt: action.prompt, actionLabel: action.label });
                      }
                    }}
                    className="inline-flex items-center gap-1.5 px-2.5 py-1.5 rounded-full text-xs font-semibold bg-slate-100 dark:bg-slate-800 hover:bg-sky-50 dark:hover:bg-sky-950/50 text-slate-700 dark:text-slate-200 hover:text-sky-700 dark:hover:text-sky-300 border border-slate-200/80 dark:border-slate-700/80 transition-all cursor-pointer disabled:opacity-50 disabled:cursor-not-allowed shadow-2xs"
                  >
                    <IconComponent className="w-3 h-3 text-sky-500 shrink-0" />
                    <span>{action.label}</span>
                  </button>
                );
              })}
            </div>
          </div>
        )}

        {/* Main Conversation Stream */}
        <div className="flex-1 overflow-y-auto p-4 sm:p-5 space-y-4 bg-slate-50/50 dark:bg-slate-950/50 min-h-0">
          {messages.length === 0 ? (
            <div className="h-full flex flex-col items-center justify-center text-center p-6 space-y-3">
              <div className="w-12 h-12 rounded-2xl bg-sky-100 dark:bg-sky-950/60 border border-sky-200 dark:border-sky-800 text-sky-600 dark:text-sky-400 flex items-center justify-center shadow-xs">
                <Sparkles className="w-6 h-6" />
              </div>
              <div className="max-w-xs space-y-1">
                <h4 className="text-sm font-bold text-slate-900 dark:text-white">
                  Operational Assistant Ready
                </h4>
                <p className="text-xs text-slate-500 dark:text-slate-400 leading-relaxed">
                  Click a quick action above or ask specific questions about Dvorak morphology, track certainty, and coastal impact.
                </p>
              </div>
              <div className="p-3 rounded-xl bg-slate-100 dark:bg-slate-900 border border-slate-200 dark:border-slate-800 text-[11px] text-slate-600 dark:text-slate-400 text-left w-full space-y-1 font-mono">
                <div className="font-bold text-slate-700 dark:text-slate-300">Suggested Questions:</div>
                <div>• "Why is this system intensifying?"</div>
                <div>• "What is the confidence of the predicted eye fix?"</div>
                <div>• "How uncertain is the 72-hour landfall timeline?"</div>
              </div>
            </div>
          ) : (
            messages.map((msg) => {
              if (msg.role === 'user') {
                return (
                  <div key={msg.id} className="flex justify-end">
                    <div className="max-w-[85%] rounded-2xl rounded-tr-xs bg-sky-600 text-white px-3.5 py-2.5 shadow-sm text-xs sm:text-[13px] leading-relaxed">
                      <p>{msg.text}</p>
                      <span className="text-[9px] text-sky-200 block text-right mt-1 font-mono">
                        {msg.timestamp}
                      </span>
                    </div>
                  </div>
                );
              }

              if (msg.role === 'error') {
                return (
                  <div key={msg.id} className="flex justify-start">
                    <div className="max-w-[90%] rounded-2xl rounded-tl-xs bg-red-50 dark:bg-red-950/40 border border-red-200 dark:border-red-900/60 p-3 text-xs text-red-700 dark:text-red-300 space-y-2">
                      <div className="flex items-center gap-1.5 font-bold">
                        <AlertTriangle className="w-4 h-4 text-red-600 shrink-0" />
                        <span>Analyst Advisory Notice</span>
                      </div>
                      <p>{msg.text}</p>
                      {msg.retryAction && (
                        <button
                          onClick={() => executeAiRequest(msg.retryAction)}
                          disabled={isLoading}
                          className="inline-flex items-center gap-1.5 px-3 py-1 rounded-lg bg-red-600 text-white font-semibold text-[11px] hover:bg-red-700 transition-colors cursor-pointer"
                        >
                          <RefreshCw className="w-3 h-3" />
                          <span>Retry Analysis</span>
                        </button>
                      )}
                    </div>
                  </div>
                );
              }

              // Assistant message
              return (
                <div key={msg.id} className="flex justify-start">
                  <div className="max-w-[92%] rounded-2xl rounded-tl-xs bg-white dark:bg-slate-900 border border-slate-200/80 dark:border-slate-800 p-3.5 sm:p-4 shadow-sm space-y-2">
                    <div className="flex items-center justify-between border-b border-slate-100 dark:border-slate-800 pb-1.5 mb-1.5">
                      <div className="flex items-center gap-1.5">
                        <span className="w-2 h-2 rounded-full bg-cyan-400" />
                        <span className="text-[10px] font-bold uppercase tracking-wider text-sky-700 dark:text-sky-300">
                          AI Interpretation
                        </span>
                      </div>
                      <span className="text-[9px] font-mono text-slate-400">
                        {msg.timestamp}
                      </span>
                    </div>

                    <FormattedMessageText text={msg.text} />

                    {/* IMD Caution Footer */}
                    <div className="pt-2 mt-2 border-t border-slate-100 dark:border-slate-800/80 text-[10px] font-mono text-slate-400 dark:text-slate-500 flex items-center gap-1">
                      <ShieldAlert className="w-3 h-3 text-amber-500 shrink-0" />
                      <span>Always reference official MoES/IMD bulletins for civil defense action.</span>
                    </div>
                  </div>
                </div>
              );
            })
          )}

          {/* Loading Indicator */}
          {isLoading && (
            <div className="flex justify-start">
              <div className="rounded-2xl rounded-tl-xs bg-white dark:bg-slate-900 border border-slate-200/80 dark:border-slate-800 p-3.5 shadow-sm flex items-center gap-3">
                <div className="w-5 h-5 border-2 border-sky-500 border-t-transparent rounded-full animate-spin" />
                <span className="text-xs font-mono text-slate-600 dark:text-slate-300">
                  Synthesizing meteorological telemetry with Puter AI...
                </span>
              </div>
            </div>
          )}

          <div ref={messagesEndRef} />
        </div>

        {/* Input Bar Form */}
        <div className="p-3 sm:p-4 border-t border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-900 shrink-0">
          <form onSubmit={handleCustomSubmit} className="flex items-center gap-2">
            <input
              ref={inputRef}
              type="text"
              value={inputText}
              disabled={!hasActiveSession || isLoading}
              onChange={e => setInputText(e.target.value)}
              placeholder={hasActiveSession ? "Ask VAYU AI Analyst about this cyclone..." : "Select cyclone to enable analyst..."}
              className="flex-1 px-3.5 py-2.5 rounded-xl text-xs sm:text-sm bg-slate-100 dark:bg-slate-800/90 border border-slate-200 dark:border-slate-700/80 text-slate-900 dark:text-white placeholder:text-slate-400 focus:outline-none focus:ring-2 focus:ring-sky-500/50 disabled:opacity-50 disabled:cursor-not-allowed"
            />
            <button
              type="submit"
              disabled={!hasActiveSession || !inputText.trim() || isLoading}
              className="p-2.5 rounded-xl bg-sky-600 hover:bg-sky-500 text-white disabled:opacity-40 disabled:cursor-not-allowed transition-colors cursor-pointer shrink-0 shadow-sm"
              title="Submit Query"
            >
              <Send className="w-4 h-4" />
            </button>
          </form>
          <div className="flex items-center justify-between text-[10px] text-slate-400 mt-2 px-1">
            <span>Powered by Puter AI & VAYU Neural Engines</span>
            <span className="font-mono">Zero auth credentials exposed</span>
          </div>
        </div>
      </aside>
    </div>
  );
}
