import React, { useState, useEffect, useRef, useMemo, useCallback } from 'react';
import { 
  X, RefreshCw, AlertTriangle, ShieldAlert, ArrowRight,
  Compass, Eye, ChevronDown, ChevronUp, RotateCcw,
  Copy, Check, Square, ThumbsUp, ThumbsDown, ArrowUp,
  Sparkles, Activity
} from 'lucide-react';
import { useAnalysisSession } from '../context/AnalysisSessionContext';
import { buildCyclonePromptContext, buildAiActionContext } from '../services/cycloneContextSerializer';
import { explainCyclone, askAnalyst } from '../services/puterAiService';

/**
 * Quick Action Prompts Configuration
 */
const QUICK_ACTIONS = [
  {
    id: 'summarize',
    label: 'Summarize Current Storm',
    icon: Sparkles,
    type: 'explain',
    description: 'Comprehensive synoptic overview and intensity assessment'
  },
  {
    id: 'dvorak',
    label: 'Explain Dvorak Analysis',
    icon: Eye,
    type: 'ask',
    prompt: 'Explain the ResNet18 Dvorak morphology classification, convective cloud pattern organization, T-number meaning, and classification confidence for this system. If classification data is missing, state "Data unavailable in current session."',
    description: 'ResNet18 pattern, Dvorak T-number, and vortex health'
  },
  {
    id: 'trajectory',
    label: 'Analyze Trajectory',
    icon: Compass,
    type: 'ask',
    prompt: 'Analyze the 72-hour trajectory forecast generated by the VAYU GRU model: movement direction, forecast milestones, major track recurvature, uncertainty growth envelope, and environmental steering factors. If trajectory data is missing, state "Data unavailable in current session."',
    description: 'GRU 72h track forecast, recurvature, and steering'
  },
  {
    id: 'landfall',
    label: 'Assess Landfall Risk',
    icon: ShieldAlert,
    type: 'ask',
    prompt: 'Assess the projected landfall risk, timing window, target coastal sector, crossing wind speed, storm surge estimate, and verified coastal strike probabilities. If landfall projection data is missing, state "Data unavailable in current session."',
    description: 'Coastal sector threat, crossing winds, and surge'
  },
  {
    id: 'confidence',
    label: 'Explain Model Confidence',
    icon: Activity,
    type: 'ask',
    prompt: 'Explain the confidence levels and uncertainties across VAYU deep learning models: MobileNetV3 center detection objectness, ResNet18 Dvorak classifier confidence, and GRU spatiotemporal kinematic uncertainty radius (MC-Dropout spread). Clearly distinguish classification confidence from kinematic track uncertainty. If any model output is unavailable, state "Data unavailable in current session."',
    description: 'Detection, classification, and GRU uncertainty spread'
  }
];

/**
 * Enhanced Safe Operational Markdown & Text Formatter.
 * Features Gemini / Claude-style top-to-bottom visibility fade and monochromatic styling.
 */
function FormattedMessageText({ text, isStreaming = false, isThinking = false }) {
  const [copiedCodeIdx, setCopiedCodeIdx] = useState(null);

  if (isThinking && !text) {
    return (
      <div className="py-1 select-none text-[13px] font-normal tracking-tight animate-stream-reveal flex items-center gap-1.5">
        <span className="bg-gradient-to-r from-slate-400 via-slate-700 to-slate-400 dark:from-slate-500 dark:via-slate-200 dark:to-slate-500 bg-clip-text text-transparent animate-shimmer font-medium">
          Thinking...
        </span>
      </div>
    );
  }

  if (!text) return null;

  // Defensive sanitization of thought blocks if any slipped through
  const cleanedText = text
    .replace(/<thought>[\s\S]*?<\/thought>/gi, '')
    .replace(/<thought>[\s\S]*$/gi, '')
    .replace(/<\/thought>/gi, '')
    .trim();

  // Parse code blocks vs regular lines
  const sections = [];
  const codeBlockRegex = /```([a-zA-Z0-9_-]*)\n([\s\S]*?)```/g;
  let lastIndex = 0;
  let match;

  while ((match = codeBlockRegex.exec(cleanedText)) !== null) {
    if (match.index > lastIndex) {
      sections.push({ type: 'text', content: cleanedText.slice(lastIndex, match.index) });
    }
    sections.push({ type: 'code', language: match[1] || 'text', code: match[2] });
    lastIndex = codeBlockRegex.lastIndex;
  }

  if (lastIndex < cleanedText.length) {
    sections.push({ type: 'text', content: cleanedText.slice(lastIndex) });
  }

  if (sections.length === 0) {
    sections.push({ type: 'text', content: cleanedText });
  }

  const handleCopyCode = (code, idx) => {
    navigator.clipboard.writeText(code);
    setCopiedCodeIdx(idx);
    setTimeout(() => setCopiedCodeIdx(null), 2000);
  };

  return (
    <div className="space-y-3 text-[13.5px] leading-relaxed select-text font-normal text-slate-800 dark:text-slate-200">
      {sections.map((section, sIdx) => {
        const isLastSection = sIdx === sections.length - 1;

        if (section.type === 'code') {
          return (
            <div key={sIdx} className="rounded-xl overflow-hidden border border-slate-200 dark:border-slate-800 bg-slate-900 text-slate-100 my-2.5 shadow-xs font-mono text-xs animate-stream-reveal">
              <div className="flex items-center justify-between px-3.5 py-1.5 bg-slate-950/80 border-b border-slate-800 text-[11px] text-slate-400">
                <span className="font-semibold uppercase tracking-wider">{section.language || 'DATA'}</span>
                <button
                  onClick={() => handleCopyCode(section.code, sIdx)}
                  className="flex items-center gap-1 hover:text-white transition-colors cursor-pointer text-[10px]"
                >
                  {copiedCodeIdx === sIdx ? (
                    <>
                      <Check className="w-3 h-3 text-emerald-400" />
                      <span className="text-emerald-400">Copied</span>
                    </>
                  ) : (
                    <>
                      <Copy className="w-3 h-3" />
                      <span>Copy</span>
                    </>
                  )}
                </button>
              </div>
              <pre className="p-3.5 overflow-x-auto whitespace-pre leading-relaxed scrollbar-none">
                <code>{section.code}</code>
              </pre>
            </div>
          );
        }

        // Parse line-by-line for text section
        const lines = section.content.split('\n');

        return (
          <div key={sIdx} className="space-y-2 animate-stream-reveal">
            {lines.map((line, lIdx) => {
              const isLastLine = isLastSection && lIdx === lines.length - 1;
              const trimmed = line.trim();

              if (!trimmed) {
                return <div key={lIdx} className="h-1.5" />;
              }

              // Section Headings (# to ####)
              if (/^#{1,6}\s+/.test(trimmed)) {
                const cleanHeading = trimmed.replace(/^#{1,6}\s*/, '');
                return (
                  <div key={lIdx} className="pt-2 pb-1 font-semibold text-slate-900 dark:text-white flex items-center gap-2 border-b border-slate-200/80 dark:border-slate-800 text-sm">
                    <span>{renderInlineFormatting(cleanHeading)}</span>
                  </div>
                );
              }

              // Standard operational assessment section headers (e.g. 1. SYNOPTIC SITUATION & INTENSITY:)
              if (/^[1-4]\.\s+[A-Z\s&]+:/.test(trimmed)) {
                return (
                  <div key={lIdx} className="pt-2 font-semibold text-slate-900 dark:text-white border-b border-slate-200/80 dark:border-slate-800 pb-1 text-sm">
                    <span>{trimmed}</span>
                  </div>
                );
              }

              // Standalone bold header line (e.g. **Verified VAYU Model Data:**)
              if (/^\*\*[^*]+\*\*[:]?$/.test(trimmed)) {
                return (
                  <div key={lIdx} className="pt-1.5 font-semibold text-slate-900 dark:text-white">
                    <span>{renderInlineFormatting(trimmed)}</span>
                  </div>
                );
              }

              // Bullet point item (•, -, *, + followed by whitespace)
              const bulletMatch = trimmed.match(/^([•\-*+]|\u2022)\s+(.*)/);
              if (bulletMatch) {
                const isIndented = line.startsWith('  ') || line.startsWith('\t');
                const bulletContent = bulletMatch[2];
                return (
                  <div key={lIdx} className={`flex items-start gap-2.5 ${isIndented ? 'pl-4' : 'pl-1'}`}>
                    <span className="text-slate-400 dark:text-slate-500 font-bold shrink-0 mt-1 leading-none text-xs">
                      •
                    </span>
                    <div className="text-slate-700 dark:text-slate-300 flex-1 leading-relaxed">
                      {renderInlineFormatting(bulletContent)}
                      {isLastLine && isStreaming && <BlinkingCursor />}
                    </div>
                  </div>
                );
              }

              // Numbered list item (e.g. 1. Item, 2. Item)
              const numMatch = trimmed.match(/^(\d+)\.\s+(.*)/);
              if (numMatch) {
                const [, num, numContent] = numMatch;
                return (
                  <div key={lIdx} className="flex items-start gap-2 pl-1">
                    <span className="text-slate-500 dark:text-slate-400 font-mono font-medium shrink-0 text-xs mt-0.5">
                      {num}.
                    </span>
                    <div className="text-slate-700 dark:text-slate-300 flex-1 leading-relaxed">
                      {renderInlineFormatting(numContent)}
                      {isLastLine && isStreaming && <BlinkingCursor />}
                    </div>
                  </div>
                );
              }

              // Standard Paragraph
              return (
                <p key={lIdx} className="text-slate-700 dark:text-slate-300 leading-relaxed">
                  {renderInlineFormatting(trimmed)}
                  {isLastLine && isStreaming && <BlinkingCursor />}
                </p>
              );
            })}
          </div>
        );
      })}
    </div>
  );
}

/**
 * Monochromatic blinking cursor indicator (Gemini/Claude/GPT style)
 */
function BlinkingCursor() {
  return (
    <span 
      className="inline-block w-1.5 h-4 ml-1 bg-slate-900 dark:bg-slate-100 rounded-xs align-middle animate-pulse" 
      aria-hidden="true" 
    />
  );
}

/**
 * Helper to render inline markdown elements safely:
 * - Bold: **text**
 * - Italic: *text*
 * - Bold+Italic: ***text***
 * - Monospace: `code`
 */
function renderInlineFormatting(str) {
  if (!str) return null;

  const tokenRegex = /(\*\*\*[^*]+?\*\*\*|\*\*[^*]+?\*\*|\*[^*]+?\*|`[^`]+?`)/g;
  const parts = str.split(tokenRegex);

  return parts.filter(Boolean).map((part, i) => {
    if (part.startsWith('***') && part.endsWith('***') && part.length >= 6) {
      return (
        <strong key={i} className="font-semibold text-slate-900 dark:text-white">
          <em className="italic">{part.slice(3, -3)}</em>
        </strong>
      );
    }

    if (part.startsWith('**') && part.endsWith('**') && part.length >= 4) {
      return (
        <strong key={i} className="font-semibold text-slate-900 dark:text-white">
          {part.slice(2, -2)}
        </strong>
      );
    }

    if (part.startsWith('*') && part.endsWith('*') && part.length >= 2) {
      return (
        <em key={i} className="italic text-slate-800 dark:text-slate-200">
          {part.slice(1, -1)}
        </em>
      );
    }

    if (part.startsWith('`') && part.endsWith('`') && part.length >= 2) {
      return (
        <code key={i} className="px-1.5 py-0.5 rounded font-mono text-xs bg-slate-100 dark:bg-slate-800 text-slate-800 dark:text-slate-200 border border-slate-200 dark:border-slate-700">
          {part.slice(1, -1)}
        </code>
      );
    }

    return part;
  });
}

/**
 * VAYU AI Analyst Drawer Component
 * ----------------------------------------------------
 * Monochromatic, minimalist conversational interface with visibility-fade streaming,
 * slim unique input bar, and animated staggered prompt cards.
 */
export default function VayuAiAnalystDrawer({ isOpen, onClose }) {
  const session = useAnalysisSession();
  const { currentInput, detectionResult, classificationResult } = session;

  const [messages, setMessages] = useState([]);
  const [inputText, setInputText] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const [isTyping, setIsTyping] = useState(false);
  const [activeSessionId, setActiveSessionId] = useState(currentInput?.sessionId);
  const [isVitalsExpanded, setIsVitalsExpanded] = useState(false);
  const [copiedMessageId, setCopiedMessageId] = useState(null);
  const [feedbackStates, setFeedbackStates] = useState({});

  const messagesEndRef = useRef(null);
  const chatScrollContainerRef = useRef(null);
  const bottomInputRef = useRef(null);
  const centerInputRef = useRef(null);

  // Typewriter streaming queue and controller references
  const streamQueueRef = useRef({
    targetText: '',
    displayedText: '',
    msgId: null,
    isApiDone: false,
    aborted: false,
    timerId: null
  });

  const pumpTickerRef = useRef(null);

  // Standardized serialized prompt context from current active session
  const promptContext = useMemo(() => {
    return buildCyclonePromptContext(session);
  }, [session]);

  const activeStormName = promptContext.storm_identification?.name || currentInput?.name;
  const hasActiveSession = Boolean(
    activeStormName &&
    (detectionResult?.cyclone_detected || classificationResult || currentInput?.sourceType === 'benchmark')
  );

  // Summary telemetry badges
  const summaryCenter = promptContext.current_observation?.estimated_center?.formatted;
  const summaryWind = promptContext.current_observation?.current_wind_speed_kmh;
  const summaryPressure = promptContext.current_observation?.current_central_pressure_hpa;
  const summaryPattern = promptContext.classification?.primary_pattern;
  const summaryTNum = promptContext.classification?.dvorak_t_number;
  const summaryLandfall = promptContext.trajectory?.landfall_projection;

  // Stop generation and halt typewriter loop immediately
  const stopTypewriter = useCallback(() => {
    const queue = streamQueueRef.current;
    queue.aborted = true;
    queue.isApiDone = true;
    if (queue.timerId) {
      clearTimeout(queue.timerId);
      queue.timerId = null;
    }

    if (queue.msgId) {
      setMessages(prev => prev.map(m => {
        if (m.id === queue.msgId) {
          return {
            ...m,
            text: queue.displayedText || queue.targetText || m.text,
            isStreaming: false,
            isThinking: false,
            wasStopped: true
          };
        }
        return m;
      }));
    }

    setIsLoading(false);
    setIsTyping(false);
  }, []);

  // Clear conversation if session changes to prevent cross-storm context leakage
  useEffect(() => {
    if (currentInput?.sessionId && currentInput.sessionId !== activeSessionId) {
      setActiveSessionId(currentInput.sessionId);
      setMessages([]);
      stopTypewriter();
    }
  }, [currentInput?.sessionId, activeSessionId, stopTypewriter]);

  // Auto-scroll to bottom of conversation during generation or new message
  const scrollToBottom = useCallback((smooth = true) => {
    if (messagesEndRef.current) {
      messagesEndRef.current.scrollIntoView({ behavior: smooth ? 'smooth' : 'auto' });
    }
  }, []);

  useEffect(() => {
    if (isOpen) {
      scrollToBottom(true);
    }
  }, [messages, isLoading, isTyping, isOpen, scrollToBottom]);

  // Focus input when opened
  useEffect(() => {
    if (isOpen && hasActiveSession) {
      setTimeout(() => {
        if (messages.length === 0) {
          centerInputRef.current?.focus();
        } else {
          bottomInputRef.current?.focus();
        }
      }, 150);
    }
  }, [isOpen, hasActiveSession, messages.length]);

  // Wire pump function into pumpTickerRef to cleanly handle recursion
  useEffect(() => {
    pumpTickerRef.current = () => {
      const queue = streamQueueRef.current;
      if (queue.aborted) return;

      const target = queue.targetText || '';
      const current = queue.displayedText || '';

      if (current.length < target.length) {
        // Fast word-level cadence for smooth visibility fade
        const backlog = target.length - current.length;
        let charsToAdd = 2;
        let delayMs = 16;

        if (backlog > 100) {
          charsToAdd = Math.min(10, backlog);
          delayMs = 10;
        } else if (backlog > 40) {
          charsToAdd = Math.min(5, backlog);
          delayMs = 14;
        } else if (backlog > 15) {
          charsToAdd = Math.min(3, backlog);
          delayMs = 16;
        } else {
          charsToAdd = 2;
          delayMs = 18;
        }

        const nextText = target.slice(0, current.length + charsToAdd);
        queue.displayedText = nextText;

        setMessages(prev => prev.map(m => {
          if (m.id === queue.msgId) {
            return {
              ...m,
              text: nextText,
              isThinking: false,
              isStreaming: true
            };
          }
          return m;
        }));

        scrollToBottom(false);

        queue.timerId = setTimeout(() => {
          pumpTickerRef.current?.();
        }, delayMs);
      } else {
        if (queue.isApiDone) {
          setMessages(prev => prev.map(m => {
            if (m.id === queue.msgId) {
              return {
                ...m,
                text: target,
                isThinking: false,
                isStreaming: false
              };
            }
            return m;
          }));
          setIsTyping(false);
          setIsLoading(false);
          scrollToBottom(true);
        } else {
          queue.timerId = setTimeout(() => {
            pumpTickerRef.current?.();
          }, 25);
        }
      }
    };
  }, [scrollToBottom]);

  /**
   * Dispatches an AI request via puterAiService with real-time streaming and typewriter rendering.
   */
  const executeAiRequest = async ({ actionType, userPrompt, actionLabel, actionId }) => {
    if (!hasActiveSession) return;
    if (isLoading || isTyping) return;

    if (streamQueueRef.current.timerId) {
      clearTimeout(streamQueueRef.current.timerId);
    }

    setIsLoading(true);
    setIsTyping(true);

    const userText = actionLabel || userPrompt;
    const userMessageId = `msg_user_${Date.now()}`;
    const aiMessageId = `msg_ai_${Date.now() + 1}`;

    streamQueueRef.current = {
      targetText: '',
      displayedText: '',
      msgId: aiMessageId,
      isApiDone: false,
      aborted: false,
      timerId: null
    };

    setMessages(prev => [
      ...prev,
      {
        id: userMessageId,
        role: 'user',
        text: userText
      },
      {
        id: aiMessageId,
        role: 'assistant',
        text: '',
        isStreaming: true,
        isThinking: true,
        promptReference: { actionType, userPrompt, actionLabel, actionId }
      }
    ]);

    const handleStreamChunk = (delta, accumulated) => {
      const queue = streamQueueRef.current;
      if (queue.aborted) return;

      queue.targetText = accumulated;

      if (!queue.timerId) {
        pumpTickerRef.current?.();
      }
    };

    // Construct targeted focused context if this is a module-specific quick action
    const targetedContext = actionId
      ? buildAiActionContext(actionId, promptContext)
      : promptContext;

    try {
      let response;
      if (actionType === 'explain') {
        response = await explainCyclone(targetedContext, {}, handleStreamChunk);
      } else {
        response = await askAnalyst(userPrompt, targetedContext, {}, handleStreamChunk);
      }

      const queue = streamQueueRef.current;
      if (queue.aborted) return;

      if (response && response.success && response.text) {
        queue.targetText = response.text;
        queue.isApiDone = true;

        if (!queue.timerId) {
          pumpTickerRef.current?.();
        }
      } else {
        const errorMsg = response?.error || 'VAYU AI Analyst is temporarily unavailable. Underlying physical neural model results remain unaffected.';
        setIsLoading(false);
        setIsTyping(false);

        setMessages(prev => prev.map(m => {
          if (m.id === aiMessageId) {
            return {
              id: aiMessageId,
              role: 'error',
              text: errorMsg,
              retryAction: { actionType, userPrompt, actionLabel, actionId }
            };
          }
          return m;
        }));
      }
    } catch (err) {
      const queue = streamQueueRef.current;
      if (queue.aborted) return;

      const errorMsg = err?.message || 'VAYU AI Analyst encountered a connection issue. Underlying model results remain active.';
      setIsLoading(false);
      setIsTyping(false);

      setMessages(prev => prev.map(m => {
        if (m.id === aiMessageId) {
          return {
            id: aiMessageId,
            role: 'error',
            text: errorMsg,
            retryAction: { actionType, userPrompt, actionLabel, actionId }
          };
        }
        return m;
      }));
    }
  };

  const handleCustomSubmit = (e) => {
    e?.preventDefault();
    if (!inputText.trim() || isLoading || isTyping) return;
    const query = inputText.trim();
    setInputText('');
    executeAiRequest({ actionType: 'ask', userPrompt: query });
  };

  const handleKeyDown = (e) => {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault();
      handleCustomSubmit();
    }
  };

  const handleCopyMessage = (msgId, text) => {
    navigator.clipboard.writeText(text);
    setCopiedMessageId(msgId);
    setTimeout(() => setCopiedMessageId(null), 2000);
  };

  const handleToggleFeedback = (msgId, type) => {
    setFeedbackStates(prev => ({
      ...prev,
      [msgId]: prev[msgId] === type ? null : type
    }));
  };

  const isGenerating = isLoading || isTyping;

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-50 flex justify-end">
      {/* Backdrop */}
      <div 
        className="fixed inset-0 bg-black/40 backdrop-blur-xs transition-opacity animate-in fade-in duration-200"
        onClick={onClose}
      />

      {/* Drawer Container - Monochromatic Obsidian/White Container */}
      <aside 
        className="relative z-10 w-full sm:w-[480px] lg:w-[540px] h-full bg-white dark:bg-slate-950 border-l border-slate-200 dark:border-slate-800 shadow-2xl flex flex-col overflow-hidden animate-in slide-in-from-right duration-300"
        onClick={e => e.stopPropagation()}
      >
        {/* Top Header - Monochromatic Minimalist Top Bar */}
        <div className="px-4 sm:px-5 py-3 border-b border-slate-100 dark:border-slate-800 flex items-center justify-between bg-white/90 dark:bg-slate-950/90 backdrop-blur-md shrink-0">
          <div className="flex items-center gap-2">
            <h3 className="font-semibold text-sm text-slate-900 dark:text-white tracking-tight">
              VAYU Analyst
            </h3>
            <span className="w-1.5 h-1.5 rounded-full bg-emerald-500" title="Connected" />
          </div>

          <div className="flex items-center gap-1">
            {messages.length > 0 && (
              <button
                onClick={() => {
                  stopTypewriter();
                  setMessages([]);
                }}
                className="p-1.5 text-slate-400 hover:text-slate-700 dark:hover:text-slate-200 hover:bg-slate-100 dark:hover:bg-slate-900 rounded-lg transition-colors cursor-pointer"
                title="New Chat"
              >
                <RotateCcw className="w-4 h-4" />
              </button>
            )}
            <button
              onClick={() => {
                stopTypewriter();
                onClose();
              }}
              className="p-1.5 text-slate-400 hover:text-slate-700 dark:hover:text-slate-200 hover:bg-slate-100 dark:hover:bg-slate-900 rounded-lg transition-colors cursor-pointer"
              title="Close"
            >
              <X className="w-4 h-4" />
            </button>
          </div>
        </div>

        {/* Compact Monochromatic Active Session Strip */}
        {hasActiveSession && (
          <div className="border-b border-slate-100 dark:border-slate-800/80 bg-slate-50/50 dark:bg-slate-900/30 text-xs shrink-0">
            <div 
              onClick={() => setIsVitalsExpanded(prev => !prev)}
              className="px-4 py-2 flex items-center justify-between cursor-pointer hover:bg-slate-100/50 dark:hover:bg-slate-900/60 select-none transition-colors"
            >
              <div className="flex items-center gap-2 min-w-0">
                <span className="font-medium text-slate-800 dark:text-slate-200 truncate text-[12px]">
                  {activeStormName}
                </span>
                <span className="text-[11px] font-mono text-slate-400 truncate">
                  ({promptContext.storm_identification?.basin || 'North Indian Ocean'})
                </span>
              </div>

              {/* Monochromatic Vitals Badges */}
              <div className="flex items-center gap-1.5 shrink-0">
                {summaryTNum && (
                  <span className="px-1.5 py-0.5 rounded font-mono text-[10.5px] font-medium bg-slate-100 dark:bg-slate-800 text-slate-700 dark:text-slate-300 border border-slate-200 dark:border-slate-700">
                    {summaryTNum}
                  </span>
                )}
                {summaryWind !== null && (
                  <span className="px-1.5 py-0.5 rounded font-mono text-[10.5px] bg-slate-100 dark:bg-slate-800 text-slate-600 dark:text-slate-400 border border-slate-200 dark:border-slate-700">
                    {summaryWind} km/h
                  </span>
                )}
                <span className="text-slate-400">
                  {isVitalsExpanded ? <ChevronUp className="w-3.5 h-3.5" /> : <ChevronDown className="w-3.5 h-3.5" />}
                </span>
              </div>
            </div>

            {/* Expandable Extended Telemetry */}
            {isVitalsExpanded && (
              <div className="px-4 pb-2.5 pt-1 border-t border-slate-100 dark:border-slate-800/60 space-y-2 animate-in fade-in duration-150">
                <div className="grid grid-cols-3 gap-2">
                  <div className="p-1.5 rounded-lg bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800">
                    <span className="text-[9px] uppercase font-mono text-slate-400 block">Center Fix</span>
                    <span className="text-xs font-mono font-semibold text-slate-800 dark:text-slate-200 truncate block">
                      {summaryCenter || 'Estimated'}
                    </span>
                  </div>
                  <div className="p-1.5 rounded-lg bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800">
                    <span className="text-[9px] uppercase font-mono text-slate-400 block">Pressure</span>
                    <span className="text-xs font-mono font-semibold text-slate-800 dark:text-slate-200 truncate block">
                      {summaryPressure ? `${summaryPressure} hPa` : 'N/A'}
                    </span>
                  </div>
                  <div className="p-1.5 rounded-lg bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800">
                    <span className="text-[9px] uppercase font-mono text-slate-400 block">Pattern</span>
                    <span className="text-xs font-mono font-semibold text-slate-800 dark:text-slate-200 truncate block">
                      {summaryPattern ? summaryPattern.split(' ')[0] : 'Not analyzed'}
                    </span>
                  </div>
                </div>

                {summaryLandfall?.is_landfall_projected && (
                  <div className="flex items-center gap-1.5 p-2 rounded-lg bg-slate-100 dark:bg-slate-900 border border-slate-200 dark:border-slate-800 text-slate-700 dark:text-slate-300 text-[11px]">
                    <ShieldAlert className="w-3.5 h-3.5 text-slate-500 shrink-0" />
                    <span className="truncate">
                      Landfall: {summaryLandfall.target_coast || 'Coastal sector'} ({summaryLandfall.estimated_time || 'Pending'})
                    </span>
                  </div>
                )}
              </div>
            )}
          </div>
        )}

        {/* Quick Follow-up Chips (Only when conversation has active messages) */}
        {hasActiveSession && messages.length > 0 && (
          <div className="px-4 py-2 border-b border-slate-100 dark:border-slate-800/80 bg-white dark:bg-slate-950 overflow-x-auto shrink-0 scrollbar-none">
            <div className="flex items-center gap-1.5 min-w-max">
              {QUICK_ACTIONS.map(action => (
                <button
                  key={action.id}
                  disabled={isGenerating}
                  onClick={() => {
                    if (action.type === 'explain') {
                      executeAiRequest({ actionType: 'explain', actionLabel: action.label, actionId: action.id });
                    } else {
                      executeAiRequest({ actionType: 'ask', userPrompt: action.prompt, actionLabel: action.label, actionId: action.id });
                    }
                  }}
                  className="inline-flex items-center gap-1 px-2.5 py-1 rounded-full text-xs font-medium bg-slate-100 hover:bg-slate-200 dark:bg-slate-900 dark:hover:bg-slate-800 text-slate-700 dark:text-slate-300 border border-slate-200/80 dark:border-slate-800 transition-colors disabled:opacity-40 cursor-pointer"
                >
                  <action.icon className="w-3 h-3 text-slate-400" />
                  <span>{action.label}</span>
                </button>
              ))}
            </div>
          </div>
        )}

        {/* Main Conversation Stream */}
        <div 
          ref={chatScrollContainerRef}
          className="flex-1 overflow-y-auto p-4 sm:p-5 space-y-5 bg-white dark:bg-slate-950 min-h-0"
        >
          {messages.length === 0 ? (
            /* GPT-Style Minimalist Centered Welcome Screen */
            <div className="h-full flex flex-col items-center justify-center text-center p-4 max-w-md mx-auto space-y-6 animate-in fade-in duration-300">
              <div className="space-y-1">
                <h4 className="text-xl sm:text-2xl font-semibold text-slate-900 dark:text-white tracking-tight">
                  How can I assist your analysis today?
                </h4>
                {activeStormName && (
                  <p className="text-xs text-slate-500 dark:text-slate-400">
                    Active Session: <span className="font-medium text-slate-700 dark:text-slate-300">{activeStormName}</span>
                  </p>
                )}
              </div>

              {/* Center Slim Input Bar */}
              <form 
                onSubmit={handleCustomSubmit} 
                className="w-full relative flex items-center rounded-xl border border-slate-200 dark:border-slate-800 bg-slate-50/80 dark:bg-slate-900/80 focus-within:border-slate-400 dark:focus-within:border-slate-600 focus-within:ring-1 focus-within:ring-slate-400/20 transition-all shadow-xs px-3 py-1.5"
              >
                <input
                  ref={centerInputRef}
                  type="text"
                  value={inputText}
                  disabled={!hasActiveSession || isGenerating}
                  onChange={e => setInputText(e.target.value)}
                  placeholder={hasActiveSession ? `Ask about ${activeStormName || 'cyclone'}...` : "Select storm to begin..."}
                  className="w-full py-1.5 text-xs sm:text-[13px] bg-transparent text-slate-900 dark:text-white placeholder:text-slate-400 focus:outline-none disabled:opacity-50"
                />
                <button
                  type="submit"
                  disabled={!hasActiveSession || !inputText.trim()}
                  className="w-7 h-7 rounded-full bg-slate-900 dark:bg-white text-white dark:text-slate-900 disabled:opacity-30 disabled:cursor-not-allowed flex items-center justify-center transition-all shrink-0 cursor-pointer"
                  title="Send"
                >
                  <ArrowUp className="w-3.5 h-3.5 stroke-[2.5]" />
                </button>
              </form>

              {/* Animated Prompt Command Options (Staggered Delays like Claude/GPT) */}
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-2 w-full text-left pt-1">
                {QUICK_ACTIONS.map((action, idx) => {
                  return (
                    <button
                      key={action.id}
                      disabled={!hasActiveSession || isGenerating}
                      style={{ animationDelay: `${(idx + 1) * 80}ms` }}
                      onClick={() => {
                        if (action.type === 'explain') {
                          executeAiRequest({ actionType: 'explain', actionLabel: action.label, actionId: action.id });
                        } else {
                          executeAiRequest({ actionType: 'ask', userPrompt: action.prompt, actionLabel: action.label, actionId: action.id });
                        }
                      }}
                      className="p-3 rounded-xl bg-slate-50/70 dark:bg-slate-900/60 border border-slate-200/80 dark:border-slate-800 hover:border-slate-400 dark:hover:border-slate-600 hover:-translate-y-0.5 transition-all text-left cursor-pointer group disabled:opacity-50 disabled:cursor-not-allowed animate-stagger-in"
                    >
                      <div className="flex items-center justify-between mb-1">
                        <span className="text-xs font-semibold text-slate-900 dark:text-white group-hover:text-black dark:group-hover:text-white">
                          {action.label}
                        </span>
                        <ArrowRight className="w-3 h-3 text-slate-400 group-hover:text-slate-800 dark:group-hover:text-slate-200 transition-transform group-hover:translate-x-0.5" />
                      </div>
                      <div className="text-[11px] text-slate-500 dark:text-slate-400 line-clamp-1 leading-snug">
                        {action.description}
                      </div>
                    </button>
                  );
                })}
              </div>
            </div>
          ) : (
            /* Message Thread */
            messages.map((msg) => {
              if (msg.role === 'user') {
                return (
                  <div key={msg.id} className="flex justify-end animate-in fade-in duration-150">
                    <div className="max-w-[85%] rounded-2xl bg-slate-100 dark:bg-slate-800/90 text-slate-900 dark:text-slate-100 border border-slate-200/70 dark:border-slate-700/60 px-3.5 py-2.5 text-[13.5px] leading-relaxed select-text shadow-2xs">
                      <p className="whitespace-pre-wrap">{msg.text}</p>
                    </div>
                  </div>
                );
              }

              if (msg.role === 'error') {
                return (
                  <div key={msg.id} className="flex justify-start animate-in fade-in duration-150">
                    <div className="max-w-[92%] rounded-xl bg-slate-100 dark:bg-slate-900 border border-slate-300 dark:border-slate-800 p-3.5 text-xs text-slate-700 dark:text-slate-300 space-y-2">
                      <div className="flex items-center gap-1.5 font-semibold text-slate-900 dark:text-white">
                        <AlertTriangle className="w-3.5 h-3.5 text-amber-500 shrink-0" />
                        <span>Notice</span>
                      </div>
                      <p className="leading-relaxed">{msg.text}</p>
                      {msg.retryAction && (
                        <button
                          onClick={() => executeAiRequest(msg.retryAction)}
                          disabled={isGenerating}
                          className="inline-flex items-center gap-1.5 px-2.5 py-1 rounded-md bg-slate-900 dark:bg-white text-white dark:text-slate-900 font-medium text-[11px] transition-colors cursor-pointer"
                        >
                          <RefreshCw className="w-3 h-3" />
                          <span>Retry</span>
                        </button>
                      )}
                    </div>
                  </div>
                );
              }

              // Monochromatic Assistant Message (No robot circle, no timestamp)
              return (
                <div key={msg.id} className="space-y-1.5 text-left animate-in fade-in duration-150">
                  <div className="flex items-center justify-between">
                    <span className="font-semibold text-xs text-slate-900 dark:text-slate-100 tracking-tight">
                      VAYU Analyst
                    </span>
                    {msg.wasStopped && (
                      <span className="text-[10px] font-mono text-slate-400 bg-slate-100 dark:bg-slate-900 px-1.5 py-0.5 rounded">
                        Stopped
                      </span>
                    )}
                  </div>

                  {/* Formatted Markdown with Visibility Fade */}
                  <FormattedMessageText 
                    text={msg.text} 
                    isStreaming={msg.isStreaming} 
                    isThinking={msg.isThinking} 
                  />

                  {/* Minimal Monochromatic Action Bar */}
                  {!msg.isStreaming && !msg.isThinking && msg.text && (
                    <div className="flex items-center gap-1 pt-1.5 text-slate-400 text-xs">
                      <button
                        onClick={() => handleCopyMessage(msg.id, msg.text)}
                        className="p-1 hover:text-slate-800 dark:hover:text-slate-200 rounded transition-colors cursor-pointer"
                        title="Copy"
                      >
                        {copiedMessageId === msg.id ? (
                          <Check className="w-3.5 h-3.5 text-emerald-500" />
                        ) : (
                          <Copy className="w-3.5 h-3.5" />
                        )}
                      </button>

                      <button
                        onClick={() => handleToggleFeedback(msg.id, 'up')}
                        className={`p-1 rounded transition-colors cursor-pointer ${feedbackStates[msg.id] === 'up' ? 'text-slate-900 dark:text-white' : 'hover:text-slate-800 dark:hover:text-slate-200'}`}
                        title="Good"
                      >
                        <ThumbsUp className="w-3.5 h-3.5" />
                      </button>

                      <button
                        onClick={() => handleToggleFeedback(msg.id, 'down')}
                        className={`p-1 rounded transition-colors cursor-pointer ${feedbackStates[msg.id] === 'down' ? 'text-slate-900 dark:text-white' : 'hover:text-slate-800 dark:hover:text-slate-200'}`}
                        title="Report issue"
                      >
                        <ThumbsDown className="w-3.5 h-3.5" />
                      </button>

                      {msg.promptReference && (
                        <button
                          onClick={() => executeAiRequest(msg.promptReference)}
                          disabled={isGenerating}
                          className="p-1 hover:text-slate-800 dark:hover:text-slate-200 rounded transition-colors cursor-pointer disabled:opacity-40"
                          title="Regenerate"
                        >
                          <RefreshCw className="w-3.5 h-3.5" />
                        </button>
                      )}
                    </div>
                  )}
                </div>
              );
            })
          )}

          <div ref={messagesEndRef} />
        </div>



        {/* Slim, Sleek, Unique Input Bar (Bottom) */}
        {messages.length > 0 && (
          <div className="p-3 border-t border-slate-100 dark:border-slate-800/80 bg-white dark:bg-slate-950 shrink-0">
            <form 
              onSubmit={handleCustomSubmit} 
              className="relative flex items-center rounded-xl border border-slate-200 dark:border-slate-800 bg-slate-50/80 dark:bg-slate-900/80 focus-within:border-slate-400 dark:focus-within:border-slate-600 focus-within:ring-1 focus-within:ring-slate-400/20 transition-all px-3 py-1.5 shadow-2xs"
            >
              <input
                ref={bottomInputRef}
                type="text"
                value={inputText}
                disabled={!hasActiveSession || isGenerating}
                onKeyDown={handleKeyDown}
                onChange={e => setInputText(e.target.value)}
                placeholder={hasActiveSession ? `Ask VAYU about ${activeStormName || 'cyclone'}...` : "Select a cyclone to begin..."}
                className="w-full py-1 text-xs sm:text-[13px] bg-transparent text-slate-900 dark:text-white placeholder:text-slate-400 focus:outline-none disabled:opacity-50"
              />

              <div className="flex items-center gap-1 shrink-0 ml-2">
                {isGenerating ? (
                  <button
                    type="button"
                    onClick={stopTypewriter}
                    className="w-7 h-7 rounded-full bg-slate-900 dark:bg-white text-white dark:text-slate-900 flex items-center justify-center transition-all cursor-pointer"
                    title="Stop"
                  >
                    <Square className="w-3 h-3 fill-current" />
                  </button>
                ) : (
                  <button
                    type="submit"
                    disabled={!hasActiveSession || !inputText.trim()}
                    className="w-7 h-7 rounded-full bg-slate-900 dark:bg-white text-white dark:text-slate-900 disabled:opacity-30 disabled:cursor-not-allowed flex items-center justify-center transition-all cursor-pointer"
                    title="Send"
                  >
                    <ArrowUp className="w-3.5 h-3.5 stroke-[2.5]" />
                  </button>
                )}
              </div>
            </form>

            {/* Clean Monochromatic Grounding Notice */}
            <div className="text-[11px] text-slate-400 dark:text-slate-500 text-center mt-2 px-2 leading-tight">
              VAYU AI synthesizes meteorological insights based on active dashboard telemetry.
            </div>
          </div>
        )}
      </aside>
    </div>
  );
}
