"""
==============================================================================
Test Suite: Supabase PostgreSQL Schema & Migration Tooling Verification
==============================================================================
Tests:
1. Supabase schema DDL structure, all 13 tables, types, PKs, FKs, and indexes.
2. Identity specification: BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY.
3. Foreign key constraints: exact relationships and prohibited FKs absent.
4. Timestamp type assignments: TEXT for observation strings, TIMESTAMPTZ for audit.
5. Flag column types: SMALLINT for application compatibility.
6. Disaster alerts schema bridging (safely handles missing columns in SQLite).
7. Timestamp parsing engine (ISO, IST, UTC, NULLs).
8. Sequence synchronization logic for non-empty vs empty tables.
9. Dry-run migration execution against canonical SQLite source.
10. Migration re-run safety and conflict handling.
==============================================================================
"""

import re
import datetime
from pathlib import Path
import pytest

from backend.database.migrate_sqlite_to_supabase import (
    SCHEMA_FILE,
    MIGRATION_TABLE_ORDER,
    TIMESTAMPTZ_COLUMNS,
    OBSERVATION_TEXT_COLUMNS,
    parse_timestamp_safely,
    run_migration,
    DEFAULT_SQLITE_PATH
)


def test_schema_file_exists():
    """Verify that backend/database/supabase_schema.sql exists and is non-empty."""
    assert SCHEMA_FILE.exists(), f"Schema file not found at {SCHEMA_FILE}"
    content = SCHEMA_FILE.read_text(encoding="utf-8")
    assert len(content) > 1000, "Schema file is suspiciously small"


def test_all_13_application_tables_in_schema():
    """Verify that all 13 application tables are declared in the DDL."""
    content = SCHEMA_FILE.read_text(encoding="utf-8")
    expected_tables = [
        "satellite_data_sources",
        "satellite_frames",
        "ocean_buoy_telemetry",
        "cyclone_events",
        "inference_logs",
        "disaster_alerts",
        "telemetry_snapshots",
        "advisory_bulletins",
        "ai_models_registry",
        "devices",
        "notification_preferences",
        "vayu_alerts",
        "alert_deliveries",
    ]

    for table in expected_tables:
        pattern = rf"CREATE\s+TABLE\s+IF\s+NOT\s+EXISTS\s+{table}\s*\("
        assert re.search(pattern, content, re.IGNORECASE), f"Table {table} not found in supabase_schema.sql"

    # sqlite_sequence must NOT be in DDL
    assert "sqlite_sequence" not in content.lower()


def test_primary_keys_use_generated_by_default():
    """Verify that all 13 tables use BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY."""
    content = SCHEMA_FILE.read_text(encoding="utf-8")
    matches = re.findall(
        r"id\s+BIGINT\s+GENERATED\s+BY\s+DEFAULT\s+AS\s+IDENTITY\s+PRIMARY\s+KEY",
        content,
        re.IGNORECASE
    )
    assert len(matches) == 13, f"Expected 13 GENERATED BY DEFAULT PKs, found {len(matches)}"

    # Ensure GENERATED ALWAYS is NOT used
    assert "GENERATED ALWAYS" not in content.upper()


def test_foreign_key_constraints_in_schema():
    """Verify required foreign keys exist and prohibited ones are omitted."""
    content = SCHEMA_FILE.read_text(encoding="utf-8")

    # 1. notification_preferences -> devices (CASCADE)
    assert "FOREIGN KEY (device_id) REFERENCES devices(device_id) ON DELETE CASCADE" in content

    # 2. alert_deliveries -> vayu_alerts
    assert "FOREIGN KEY (alert_id) REFERENCES vayu_alerts(alert_id)" in content

    # 3. alert_deliveries -> devices
    assert "FOREIGN KEY (device_id) REFERENCES devices(device_id)" in content

    # Prohibited foreign keys:
    # satellite_frames.source_id -> satellite_data_sources must NOT be an enforced FK
    assert "REFERENCES satellite_data_sources" not in content

    # vayu_alerts.storm_id -> cyclone_events must NOT be an enforced FK
    assert "REFERENCES cyclone_events" not in content


def test_disaster_alerts_schema_includes_all_application_columns():
    """Verify disaster_alerts in PostgreSQL contains the 4 CAP columns missing in SQLite."""
    content = SCHEMA_FILE.read_text(encoding="utf-8")
    
    # Extract disaster_alerts table definition block
    match = re.search(r"CREATE\s+TABLE\s+IF\s+NOT\s+EXISTS\s+disaster_alerts\s*\((.*?)\);", content, re.DOTALL | re.IGNORECASE)
    assert match, "disaster_alerts table DDL block not found"
    ddl_block = match.group(1)

    assert "cap_identifier TEXT" in ddl_block
    assert "cap_urgency TEXT" in ddl_block
    assert "cap_severity TEXT" in ddl_block
    assert "cap_certainty TEXT" in ddl_block


def test_timestamp_handling_in_schema():
    """Verify observation timestamps are TEXT while system audit timestamps are TIMESTAMPTZ."""
    content = SCHEMA_FILE.read_text(encoding="utf-8")

    # Observation timestamps must be TEXT
    assert re.search(r"timestamp\s+TEXT\s+NOT\s+NULL", content, re.IGNORECASE)
    assert re.search(r"landfall_time\s+TEXT", content, re.IGNORECASE)

    # System audit timestamps must be TIMESTAMPTZ
    for ts_col in ["created_at", "updated_at", "ingested_at", "recorded_at", "issued_at", "expires_at"]:
        pattern = rf"{ts_col}\s+TIMESTAMPTZ"
        assert re.search(pattern, content, re.IGNORECASE), f"{ts_col} should be TIMESTAMPTZ"


def test_flag_columns_use_smallint():
    """Verify that boolean flag columns use SMALLINT for backward compatibility."""
    content = SCHEMA_FILE.read_text(encoding="utf-8")
    flags = [
        "is_active",
        "enable_critical",
        "enable_warning",
        "enable_watch",
        "enable_info",
        "enable_test",
        "enable_sound",
        "enable_vibration",
        "active"
    ]
    for flag in flags:
        pattern = rf"{flag}\s+SMALLINT"
        assert re.search(pattern, content, re.IGNORECASE), f"Flag {flag} should use SMALLINT"


def test_timestamp_parser_formats():
    """Verify safe parsing of timestamps across varied SQLite source formats."""
    # Standard ISO format
    dt1 = parse_timestamp_safely("2026-09-20 15:03:53")
    assert dt1 is not None
    assert dt1.year == 2026 and dt1.month == 9 and dt1.day == 20
    assert dt1.tzinfo == datetime.timezone.utc

    # ISO with Z
    dt2 = parse_timestamp_safely("2026-09-20T15:26:50Z")
    assert dt2 is not None
    assert dt2.minute == 26 and dt2.second == 50

    # IST string
    dt3 = parse_timestamp_safely("2026-09-02 12:00:00 IST")
    assert dt3 is not None
    assert dt3.hour == 12

    # None / empty preservation
    assert parse_timestamp_safely(None) is None
    assert parse_timestamp_safely("") is None


def test_dry_run_migration_against_sqlite():
    """Verify dry-run migration audits the canonical SQLite database successfully."""
    success = run_migration(
        database_url="",
        sqlite_path=DEFAULT_SQLITE_PATH,
        dry_run=True
    )
    assert success is True


def test_migration_table_order_respects_dependencies():
    """Verify parent tables precede child tables in MIGRATION_TABLE_ORDER."""
    devices_idx = MIGRATION_TABLE_ORDER.index("devices")
    vayu_alerts_idx = MIGRATION_TABLE_ORDER.index("vayu_alerts")
    notif_prefs_idx = MIGRATION_TABLE_ORDER.index("notification_preferences")
    deliveries_idx = MIGRATION_TABLE_ORDER.index("alert_deliveries")

    assert devices_idx < notif_prefs_idx, "devices must precede notification_preferences"
    assert devices_idx < deliveries_idx, "devices must precede alert_deliveries"
    assert vayu_alerts_idx < deliveries_idx, "vayu_alerts must precede alert_deliveries"
