#!/usr/bin/env python3
"""
==============================================================================
VAYU — SQLite to Supabase PostgreSQL Safe Migration Tool
==============================================================================
Safely migrates the canonical SQLite database (cyclone_intel.db) to Supabase
PostgreSQL while preserving IDs, foreign keys, timestamps, and schema integrity.

Features:
- Idempotent and safe to re-run (uses ON CONFLICT DO NOTHING).
- Strictly preserves existing primary-key IDs via GENERATED BY DEFAULT AS IDENTITY.
- Preserves observation timestamp strings and converts system timestamps to TIMESTAMPTZ.
- Bridges the disaster_alerts column mismatch safely without modifying source SQLite.
- Synchronizes identity sequences correctly for both empty and populated tables.
- Read-only source access: NEVER modifies the SQLite database.
- Validates row counts and foreign-key integrity post-migration.

Usage:
  # Standard migration using DATABASE_URL environment variable:
  python backend/database/migrate_sqlite_to_supabase.py

  # With explicit database URL:
  python backend/database/migrate_sqlite_to_supabase.py --database-url "postgresql://..."

  # Verification-only mode (checks target state without inserting):
  python backend/database/migrate_sqlite_to_supabase.py --verify-only

  # Dry-run mode (reads and validates SQLite source without writing to Postgres):
  python backend/database/migrate_sqlite_to_supabase.py --dry-run
==============================================================================
"""

import os
import sys
import argparse
import sqlite3
import datetime
from pathlib import Path
from typing import Dict, List, Any, Optional, Tuple

# Optional psycopg import with graceful error message
try:
    import psycopg
    from psycopg.rows import dict_row
except ImportError:
    psycopg = None

# Anchored paths
SCRIPT_DIR = Path(__file__).resolve().parent
BACKEND_DIR = SCRIPT_DIR.parent
ROOT_DIR = BACKEND_DIR.parent
SCHEMA_FILE = SCRIPT_DIR / "supabase_schema.sql"

# Import canonical path resolver if available
try:
    sys.path.insert(0, str(ROOT_DIR))
    from backend.database.db_manager import resolve_database_path
    DEFAULT_SQLITE_PATH = resolve_database_path()
except Exception:
    DEFAULT_SQLITE_PATH = SCRIPT_DIR / "cyclone_intel.db"

# Strict table migration order (parent tables before dependent child tables)
MIGRATION_TABLE_ORDER = [
    # 1. Independent parent catalogs & references
    "satellite_data_sources",
    "cyclone_events",
    "ai_models_registry",
    "disaster_alerts",
    "telemetry_snapshots",
    "advisory_bulletins",
    "inference_logs",
    "ocean_buoy_telemetry",
    "satellite_frames",
    # 2. Base entity tables
    "devices",
    "vayu_alerts",
    # 3. Dependent child tables (foreign keys enforced)
    "notification_preferences",
    "alert_deliveries",
]

# System audit timestamp columns requiring TIMESTAMPTZ parsing
TIMESTAMPTZ_COLUMNS = {
    "created_at",
    "updated_at",
    "ingested_at",
    "recorded_at",
    "issued_at",
    "captured_at",
    "registered_at",
    "attempted_at",
    "acknowledged_at",
    "expires_at",
}

# Observation timestamp columns preserved as raw TEXT strings
OBSERVATION_TEXT_COLUMNS = {
    "timestamp",
    "landfall_time",
}

def normalize_postgres_url(raw_url: str) -> str:
    """Safely normalizes PostgreSQL connection URI, encoding special characters in password if needed."""
    if not raw_url:
        return ""
    url = raw_url.strip()
    if url.startswith("postgresql+psycopg://"):
        url = url.replace("postgresql+psycopg://", "postgresql://", 1)

    # Check if password has unencoded '@' (e.g. postgresql://user:p@ss@host:port/db)
    if url.count("@") > 1 and "://" in url:
        prefix, rest = url.split("://", 1)
        userinfo, hostinfo = rest.rsplit("@", 1)
        if ":" in userinfo:
            user, password = userinfo.split(":", 1)
            import urllib.parse
            encoded_password = urllib.parse.quote(password, safe="")
            url = f"{prefix}://{user}:{encoded_password}@{hostinfo}"
    return url


def parse_timestamp_safely(val: Any) -> Optional[datetime.datetime]:
    """
    Safely parses diverse SQLite timestamp formats to timezone-aware UTC datetime.
    Preserves NULLs.
    """
    if val is None or val == "":
        return None
    if isinstance(val, datetime.datetime):
        if val.tzinfo is None:
            return val.replace(tzinfo=datetime.timezone.utc)
        return val

    val_str = str(val).strip()

    # Standard ISO formats
    iso_formats = [
        "%Y-%m-%d %H:%M:%S",
        "%Y-%m-%d %H:%M:%S.%f",
        "%Y-%m-%dT%H:%M:%SZ",
        "%Y-%m-%dT%H:%M:%S",
        "%Y-%m-%dT%H:%M:%S.%fZ",
        "%Y-%m-%dT%H:%M:%S%z",
    ]

    for fmt in iso_formats:
        try:
            dt = datetime.datetime.strptime(val_str, fmt)
            if dt.tzinfo is None:
                dt = dt.replace(tzinfo=datetime.timezone.utc)
            return dt
        except ValueError:
            continue

    # If format contains 'IST' or other suffix, attempt best-effort parse
    if "IST" in val_str:
        clean = val_str.replace("IST", "").strip()
        try:
            dt = datetime.datetime.strptime(clean, "%Y-%m-%d %H:%M:%S")
            # IST is UTC+5:30
            tz_ist = datetime.timezone(datetime.timedelta(hours=5, minutes=30))
            return dt.replace(tzinfo=tz_ist)
        except ValueError:
            pass

    return None


def get_sqlite_connection(db_path: Path) -> sqlite3.Connection:
    """Opens a strictly READ-ONLY connection to SQLite to prevent accidental mutations."""
    if not db_path.exists():
        raise FileNotFoundError(f"Canonical SQLite database not found at: {db_path}")
    
    uri_path = f"file:{db_path.resolve().as_posix()}?mode=ro"
    conn = sqlite3.connect(uri_path, uri=True, check_same_thread=False)
    conn.row_factory = sqlite3.Row
    return conn


def apply_schema(pg_conn: Any, schema_path: Path) -> None:
    """Executes the DDL schema file on Supabase PostgreSQL."""
    if not schema_path.exists():
        raise FileNotFoundError(f"Supabase schema file not found at: {schema_path}")

    with open(schema_path, "r", encoding="utf-8") as f:
        ddl = f.read()

    with pg_conn.cursor() as cur:
        cur.execute(ddl)
    pg_conn.commit()


def get_table_columns(cur: Any, table_name: str) -> List[str]:
    """Retrieves column names for a PostgreSQL table from information_schema."""
    cur.execute("""
        SELECT column_name
        FROM information_schema.columns
        WHERE table_schema = 'public' AND table_name = %s
        ORDER BY ordinal_position;
    """, (table_name,))
    return [r["column_name"] for r in cur.fetchall()]


def migrate_table(
    sqlite_conn: sqlite3.Connection,
    pg_conn: Any,
    table_name: str,
    dry_run: bool = False
) -> Tuple[int, int]:
    """
    Migrates rows from a single SQLite table to Supabase PostgreSQL.
    Returns: (sqlite_row_count, postgres_row_count)
    """
    # 1. Fetch SQLite rows and source schema
    s_cur = sqlite_conn.cursor()
    s_cur.execute(f"PRAGMA table_info({table_name});")
    sqlite_cols = [r[1] for r in s_cur.fetchall()]

    s_cur.execute(f"SELECT COUNT(*) FROM {table_name};")
    sqlite_count = s_cur.fetchone()[0]

    s_cur.execute(f"SELECT * FROM {table_name} ORDER BY id ASC;")
    sqlite_rows = s_cur.fetchall()

    if dry_run:
        return sqlite_count, 0

    # 2. Fetch destination PostgreSQL columns
    with pg_conn.cursor(row_factory=dict_row) as pg_cur:
        pg_cols = get_table_columns(pg_cur, table_name)
        if not pg_cols:
            raise RuntimeError(f"Target table public.{table_name} does not exist in PostgreSQL.")

    if not sqlite_rows:
        # Table is empty, nothing to insert
        with pg_conn.cursor() as pg_cur:
            pg_cur.execute(f"SELECT COUNT(*) FROM {table_name};")
            pg_count = pg_cur.fetchone()[0]
        return 0, pg_count

    # 3. Prepare column mapping and bridge missing columns (e.g. disaster_alerts)
    insert_cols = []
    for c in pg_cols:
        insert_cols.append(c)

    col_names_str = ", ".join(insert_cols)
    placeholders_str = ", ".join(["%s"] * len(insert_cols))
    
    # Idempotent upsert: on conflict on ID, do nothing (preserves original migrated row)
    insert_sql = f"""
        INSERT INTO {table_name} ({col_names_str})
        VALUES ({placeholders_str})
        ON CONFLICT (id) DO NOTHING;
    """

    # 4. Transform and insert records
    records_to_insert = []
    for row in sqlite_rows:
        row_dict = dict(row)
        record = []

        for col in insert_cols:
            if col in row_dict:
                val = row_dict[col]
                # Timestamp conversion for audit columns
                if col in TIMESTAMPTZ_COLUMNS and col not in OBSERVATION_TEXT_COLUMNS:
                    val = parse_timestamp_safely(val)
                record.append(val)
            else:
                # Column exists in PostgreSQL but not in SQLite (e.g. disaster_alerts CAP fields)
                if col == "cap_identifier":
                    record.append(None)
                elif col == "cap_urgency":
                    record.append("Immediate")
                elif col == "cap_severity":
                    record.append("Extreme")
                elif col == "cap_certainty":
                    record.append("Observed")
                else:
                    record.append(None)

        records_to_insert.append(tuple(record))

    with pg_conn.cursor() as pg_cur:
        pg_cur.executemany(insert_sql, records_to_insert)
    pg_conn.commit()

    # 5. Fetch resulting PostgreSQL count
    with pg_conn.cursor() as pg_cur:
        pg_cur.execute(f"SELECT COUNT(*) FROM {table_name};")
        pg_count = pg_cur.fetchone()[0]

    return sqlite_count, pg_count


def sync_identity_sequence(pg_conn: Any, table_name: str) -> None:
    """
    Synchronizes PostgreSQL identity sequence with current table max(id).
    Properly handles both populated and empty tables.
    """
    with pg_conn.cursor() as cur:
        # Check if table has rows
        cur.execute(f"SELECT MAX(id) FROM {table_name};")
        max_id = cur.fetchone()[0]

        if max_id is not None:
            # Table is populated: nextval will return max_id + 1
            cur.execute(f"""
                SELECT setval(pg_get_serial_sequence('{table_name}', 'id'), %s, true);
            """, (max_id,))
        else:
            # Table is empty: setval with is_called = false so nextval generates 1
            cur.execute(f"""
                SELECT setval(pg_get_serial_sequence('{table_name}', 'id'), 1, false);
            """)
    pg_conn.commit()


def validate_foreign_keys(pg_conn: Any) -> List[str]:
    """Validates that no orphan records exist across PostgreSQL foreign-key relationships."""
    errors = []
    checks = [
        (
            "notification_preferences.device_id -> devices.device_id",
            """
            SELECT np.device_id FROM notification_preferences np
            LEFT JOIN devices d ON np.device_id = d.device_id
            WHERE d.device_id IS NULL;
            """
        ),
        (
            "alert_deliveries.device_id -> devices.device_id",
            """
            SELECT ad.device_id FROM alert_deliveries ad
            LEFT JOIN devices d ON ad.device_id = d.device_id
            WHERE d.device_id IS NULL;
            """
        ),
        (
            "alert_deliveries.alert_id -> vayu_alerts.alert_id",
            """
            SELECT ad.alert_id FROM alert_deliveries ad
            LEFT JOIN vayu_alerts va ON ad.alert_id = va.alert_id
            WHERE va.alert_id IS NULL;
            """
        ),
    ]

    with pg_conn.cursor(row_factory=dict_row) as cur:
        for desc, sql in checks:
            cur.execute(sql)
            orphans = cur.fetchall()
            if orphans:
                errors.append(f"Foreign-key check failed for {desc}: {len(orphans)} orphan records found.")

    return errors


def run_migration(
    database_url: str,
    sqlite_path: Path = DEFAULT_SQLITE_PATH,
    dry_run: bool = False,
    verify_only: bool = False
) -> bool:
    """Executes the complete migration workflow and prints detailed audit telemetry."""
    print("=" * 80)
    print(" VAYU — SQLITE TO SUPABASE POSTGRESQL MIGRATION ENGINE")
    print(" Team Chakravat Crew (SIH 2026)")
    print("=" * 80)
    print(f" Source SQLite Database: {sqlite_path}")
    print(f" Mode: {'DRY RUN' if dry_run else 'VERIFY ONLY' if verify_only else 'FULL MIGRATION'}")
    print("-" * 80)

    # 1. Connect to SQLite (strictly read-only)
    try:
        sqlite_conn = get_sqlite_connection(sqlite_path)
        print("✓ Connected to SQLite source database in read-only mode.")
    except Exception as e:
        print(f"✗ Failed to open SQLite source: {e}")
        return False

    if dry_run:
        print("\n[DRY RUN AUDIT — Source Table Row Counts]")
        total_rows = 0
        s_cur = sqlite_conn.cursor()
        for tbl in MIGRATION_TABLE_ORDER:
            s_cur.execute(f"SELECT COUNT(*) FROM {tbl};")
            cnt = s_cur.fetchone()[0]
            total_rows += cnt
            print(f"  - {tbl:28}: {cnt:5} rows")
        print(f"\nTotal rows ready for migration: {total_rows}")
        sqlite_conn.close()
        print("✓ Dry run completed successfully. Source SQLite was not modified.")
        return True

    # 2. Connect to Supabase PostgreSQL
    if not psycopg:
        print("✗ psycopg library is required. Install via: pip install 'psycopg[binary]>=3.2.0'")
        sqlite_conn.close()
        return False

    if not database_url:
        print("✗ DATABASE_URL is missing. Please set the environment variable or pass --database-url.")
        sqlite_conn.close()
        return False
    pg_url = normalize_postgres_url(database_url)
    try:
        pg_conn = psycopg.connect(pg_url, autocommit=False)
        print("✓ Connected to target Supabase PostgreSQL database.")
    except Exception as e:
        print(f"✗ Failed to connect to PostgreSQL: {e}")
        sqlite_conn.close()
        return False

    try:
        # 3. Apply DDL Schema
        if not verify_only:
            print("\nApplying Supabase PostgreSQL schema...")
            apply_schema(pg_conn, SCHEMA_FILE)
            print("✓ PostgreSQL schema verified/created successfully.")

        # 4. Migrate tables in dependency order
        print("\n[Migrating Tables]")
        summary = []
        has_discrepancy = False

        for table in MIGRATION_TABLE_ORDER:
            if verify_only:
                s_cur = sqlite_conn.cursor()
                s_cur.execute(f"SELECT COUNT(*) FROM {table};")
                s_cnt = s_cur.fetchone()[0]
                with pg_conn.cursor() as p_cur:
                    p_cur.execute(f"SELECT COUNT(*) FROM {table};")
                    p_cnt = p_cur.fetchone()[0]
            else:
                s_cnt, p_cnt = migrate_table(sqlite_conn, pg_conn, table, dry_run=False)
                # Synchronize sequence
                sync_identity_sequence(pg_conn, table)

            match = (s_cnt == p_cnt)
            if not match and p_cnt < s_cnt:
                has_discrepancy = True
            
            status_icon = "✓" if match else "!"
            print(f"  {status_icon} {table:28}: SQLite={s_cnt:5}  →  PostgreSQL={p_cnt:5}")
            summary.append((table, s_cnt, p_cnt, match))

        # 5. Validate foreign-key integrity
        print("\n[Validating Foreign Key Constraints]")
        fk_errors = validate_foreign_keys(pg_conn)
        if fk_errors:
            for err in fk_errors:
                print(f"  ✗ {err}")
            has_discrepancy = True
        else:
            print("  ✓ All foreign-key relationships valid (0 orphan records).")

        # 6. Final report
        print("\n" + "=" * 80)
        if not has_discrepancy:
            print(" MIGRATION SUCCESSFUL: All tables synchronized with 100% data integrity.")
        else:
            print(" WARNING: Some row counts or foreign keys require inspection.")
        print("=" * 80)

        return not has_discrepancy

    finally:
        sqlite_conn.close()
        pg_conn.close()


def main():
    parser = argparse.ArgumentParser(description="VAYU SQLite to Supabase PostgreSQL Migration Tool")
    parser.add_argument("--database-url", help="Supabase PostgreSQL connection URI (defaults to DATABASE_URL env var)")
    parser.add_argument("--sqlite-path", type=Path, default=DEFAULT_SQLITE_PATH, help="Path to source SQLite database")
    parser.add_argument("--dry-run", action="store_true", help="Audit SQLite source without writing to PostgreSQL")
    parser.add_argument("--verify-only", action="store_true", help="Compare existing PostgreSQL tables against SQLite without inserting")

    args = parser.parse_args()

    db_url = args.database_url or os.environ.get("DATABASE_URL")
    if not db_url:
        vayu_env = Path.home() / ".config/vayu/supabase.env"
        if vayu_env.exists():
            for line in vayu_env.read_text(encoding="utf-8").splitlines():
                if line.startswith("DATABASE_URL="):
                    db_url = line.split("=", 1)[1].strip().strip('"').strip("'")
                    break

    success = run_migration(
        database_url=db_url,
        sqlite_path=args.sqlite_path,
        dry_run=args.dry_run,
        verify_only=args.verify_only
    )

    sys.exit(0 if success else 1)


if __name__ == "__main__":
    main()
