-- ==============================================================================
-- VAYU ENTERPRISE INTELLIGENCE GATEWAY — SUPABASE POSTGRESQL SCHEMA
-- Multi-Source Satellite & Cyclone Spatiotemporal Prediction Platform (SIH 2026)
--
-- TARGET: Supabase PostgreSQL (v15+)
-- NOTES:
-- 1. Uses BIGINT GENERATED BY DEFAULT AS IDENTITY to preserve existing SQLite IDs.
-- 2. Observation timestamps with meteorological strings ('... IST') preserved as TEXT.
-- 3. System audit timestamps use TIMESTAMPTZ.
-- 4. Status flags use SMALLINT (0/1) for seamless Python/SQLite backward compatibility.
-- 5. Strict foreign keys enforced only on validated entity relationships.
-- ==============================================================================

-- ------------------------------------------------------------------------------
-- 1. SATELLITE DATA SOURCES
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS satellite_data_sources (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_id TEXT UNIQUE NOT NULL,
    agency TEXT NOT NULL,
    satellite_name TEXT NOT NULL,
    orbit_type TEXT NOT NULL,
    spectral_channels_json TEXT NOT NULL,
    spatial_resolution_km DOUBLE PRECISION NOT NULL,
    temporal_cadence_min INTEGER NOT NULL,
    status TEXT DEFAULT 'ONLINE',
    data_format TEXT DEFAULT 'HDF5 / NetCDF-4',
    coverage_basin TEXT DEFAULT 'North Indian Ocean',
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- ------------------------------------------------------------------------------
-- 2. SATELLITE FRAMES (Logical ref to satellite_data_sources.source_id)
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS satellite_frames (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_id TEXT NOT NULL,
    channel TEXT NOT NULL,
    timestamp TEXT NOT NULL, -- Meteorological string e.g. '2026-09-02 23:15:45 IST'
    basin TEXT NOT NULL,
    center_lat DOUBLE PRECISION NOT NULL,
    center_lon DOUBLE PRECISION NOT NULL,
    min_brightness_temp_c DOUBLE PRECISION NOT NULL,
    avg_brightness_temp_c DOUBLE PRECISION NOT NULL,
    convective_cloud_fraction DOUBLE PRECISION NOT NULL,
    storage_path TEXT,
    metadata_json TEXT,
    ingested_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_satellite_frames_source_ingested 
    ON satellite_frames(source_id, ingested_at DESC);

-- ------------------------------------------------------------------------------
-- 3. OCEAN BUOY & SCATTEROMETER TELEMETRY
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS ocean_buoy_telemetry (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    buoy_id TEXT NOT NULL,
    agency TEXT DEFAULT 'INCOIS / NIOT',
    latitude DOUBLE PRECISION NOT NULL,
    longitude DOUBLE PRECISION NOT NULL,
    basin TEXT NOT NULL,
    sea_surface_temp_c DOUBLE PRECISION NOT NULL,
    sea_surface_pressure_hpa DOUBLE PRECISION NOT NULL,
    surface_wind_speed_kmh DOUBLE PRECISION NOT NULL,
    surface_wind_direction_deg DOUBLE PRECISION NOT NULL,
    significant_wave_height_m DOUBLE PRECISION NOT NULL,
    ocean_heat_content_kj_cm2 DOUBLE PRECISION NOT NULL,
    salinity_psu DOUBLE PRECISION DEFAULT 34.5,
    timestamp TEXT NOT NULL, -- Observation timestamp string e.g. '2026-09-02 12:00:00 IST'
    recorded_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_ocean_buoy_basin_recorded 
    ON ocean_buoy_telemetry(basin, recorded_at DESC);

-- ------------------------------------------------------------------------------
-- 4. CYCLONE EVENTS & TRACKS
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS cyclone_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    system_id TEXT UNIQUE NOT NULL,
    name TEXT NOT NULL,
    season TEXT NOT NULL,
    basin TEXT NOT NULL,
    category TEXT NOT NULL,
    status TEXT DEFAULT 'ACTIVE',
    peak_intensity_kmh DOUBLE PRECISION NOT NULL,
    peak_intensity_knots DOUBLE PRECISION NOT NULL,
    lowest_mslp_hpa DOUBLE PRECISION NOT NULL,
    landfall_location TEXT,
    landfall_time TEXT, -- Text meteorological string
    landfall_lat DOUBLE PRECISION,
    landfall_lon DOUBLE PRECISION,
    surge_height_m DOUBLE PRECISION,
    dvorak_ci TEXT,
    description TEXT,
    track_history_json TEXT,
    track_forecast_json TEXT,
    cone_polygon_json TEXT,
    impact_districts_json TEXT,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_cyclone_events_basin_created 
    ON cyclone_events(basin, created_at DESC);

-- ------------------------------------------------------------------------------
-- 5. AI INFERENCE LOGS
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS inference_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    model_name TEXT NOT NULL,
    model_version TEXT NOT NULL,
    inference_type TEXT NOT NULL,
    basin TEXT NOT NULL,
    input_source TEXT NOT NULL,
    detected_lat DOUBLE PRECISION,
    detected_lon DOUBLE PRECISION,
    confidence DOUBLE PRECISION NOT NULL,
    dvorak_t TEXT,
    dvorak_ci DOUBLE PRECISION,
    estimated_wind_kmh DOUBLE PRECISION,
    estimated_mslp_hpa DOUBLE PRECISION,
    morphology_pattern TEXT,
    execution_time_ms DOUBLE PRECISION NOT NULL,
    metadata_json TEXT,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_inference_logs_created 
    ON inference_logs(created_at DESC);

-- ------------------------------------------------------------------------------
-- 6. DISASTER ALERTS (OASIS-CAP FORMAT WITH ALL APPLICATION COLUMNS)
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS disaster_alerts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alert_level TEXT NOT NULL,
    basin TEXT NOT NULL,
    cyclone_name TEXT NOT NULL,
    affected_districts_json TEXT,
    affected_states_json TEXT,
    wind_gust_forecast_kmh DOUBLE PRECISION,
    surge_height_m TEXT,
    rainfall_24h_mm DOUBLE PRECISION,
    evacuation_recommendation TEXT,
    cap_identifier TEXT,
    cap_urgency TEXT DEFAULT 'Immediate',
    cap_severity TEXT DEFAULT 'Extreme',
    cap_certainty TEXT DEFAULT 'Observed',
    issued_by TEXT,
    active SMALLINT DEFAULT 1,
    issued_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_disaster_alerts_issued 
    ON disaster_alerts(issued_at DESC);

-- ------------------------------------------------------------------------------
-- 7. TELEMETRY SNAPSHOTS
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS telemetry_snapshots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    satellite_source TEXT NOT NULL,
    basin TEXT NOT NULL,
    center_lat DOUBLE PRECISION,
    center_lon DOUBLE PRECISION,
    sst_celsius DOUBLE PRECISION,
    vertical_wind_shear_knots DOUBLE PRECISION,
    mslp_hpa DOUBLE PRECISION,
    surface_wind_kmh DOUBLE PRECISION,
    raw_payload_json TEXT,
    captured_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- ------------------------------------------------------------------------------
-- 8. ADVISORY BULLETINS
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS advisory_bulletins (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bulletin_no TEXT UNIQUE NOT NULL,
    cyclone_name TEXT NOT NULL,
    basin TEXT NOT NULL,
    category TEXT NOT NULL,
    issued_by TEXT NOT NULL,
    pdf_size_bytes BIGINT NOT NULL,
    issued_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- ------------------------------------------------------------------------------
-- 9. AI MODELS REGISTRY
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS ai_models_registry (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    model_key TEXT UNIQUE NOT NULL,
    model_name TEXT NOT NULL,
    version TEXT NOT NULL,
    backbone TEXT NOT NULL,
    dataset_trained TEXT NOT NULL,
    mae_track_km DOUBLE PRECISION,
    accuracy_pct DOUBLE PRECISION,
    parameters_count TEXT,
    is_active SMALLINT DEFAULT 1,
    registered_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- ------------------------------------------------------------------------------
-- 10. CLIENT DEVICES (Phase 10 Foundation)
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS devices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id TEXT UNIQUE NOT NULL,
    fcm_token TEXT NOT NULL,
    platform TEXT DEFAULT 'android',
    app_version TEXT,
    os_version TEXT,
    device_model TEXT,
    locale TEXT DEFAULT 'en_IN',
    last_known_lat DOUBLE PRECISION,
    last_known_lon DOUBLE PRECISION,
    last_known_district TEXT,
    last_known_state TEXT,
    is_active SMALLINT DEFAULT 1,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_devices_active_updated 
    ON devices(is_active, updated_at DESC);

-- ------------------------------------------------------------------------------
-- 11. NOTIFICATION PREFERENCES (Phase 10 — Cascades with Device)
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS notification_preferences (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id TEXT UNIQUE NOT NULL,
    enable_critical SMALLINT DEFAULT 1,
    enable_warning SMALLINT DEFAULT 1,
    enable_watch SMALLINT DEFAULT 1,
    enable_info SMALLINT DEFAULT 0,
    enable_test SMALLINT DEFAULT 0,
    enable_sound SMALLINT DEFAULT 1,
    enable_vibration SMALLINT DEFAULT 1,
    subscribed_basins_json TEXT DEFAULT '["Bay of Bengal","Arabian Sea"]',
    subscribed_states_json TEXT DEFAULT '[]',
    max_alert_radius_km DOUBLE PRECISION DEFAULT 300.0,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_notification_prefs_device 
        FOREIGN KEY (device_id) REFERENCES devices(device_id) ON DELETE CASCADE
);

-- ------------------------------------------------------------------------------
-- 12. STANDARDIZED VAYU ALERTS (Phase 10)
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS vayu_alerts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alert_id TEXT UNIQUE NOT NULL,
    storm_id TEXT, -- Logical storm tag (e.g. 'DANA', 'BIPARJOY', 'TEST-DRILL')
    storm_name TEXT NOT NULL,
    severity TEXT NOT NULL,
    title TEXT NOT NULL,
    message TEXT NOT NULL,
    source TEXT NOT NULL,
    source_module TEXT,
    location_region TEXT,
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    radius_km DOUBLE PRECISION DEFAULT 150.0,
    metadata_json TEXT DEFAULT '{}',
    is_active SMALLINT DEFAULT 1,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMPTZ NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_vayu_alerts_active_created 
    ON vayu_alerts(is_active, created_at DESC);

-- ------------------------------------------------------------------------------
-- 13. ALERT DELIVERY AUDIT TRAIL (Phase 10)
-- ------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS alert_deliveries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alert_id TEXT NOT NULL,
    device_id TEXT NOT NULL,
    delivery_status TEXT DEFAULT 'QUEUED',
    fcm_message_id TEXT,
    error_message TEXT,
    attempted_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    acknowledged_at TIMESTAMPTZ,
    CONSTRAINT fk_alert_deliveries_alert 
        FOREIGN KEY (alert_id) REFERENCES vayu_alerts(alert_id),
    CONSTRAINT fk_alert_deliveries_device 
        FOREIGN KEY (device_id) REFERENCES devices(device_id)
);
CREATE INDEX IF NOT EXISTS idx_alert_deliveries_alert_device 
    ON alert_deliveries(alert_id, device_id);
CREATE INDEX IF NOT EXISTS idx_alert_deliveries_attempted 
    ON alert_deliveries(attempted_at DESC);
